/**
 * MainThread Proxy Registry — registers all MainThread proxies with the EH server.
 *
 * W1-W2: Core services (10 proxies)
 * W3:    Language features, diagnostics, documents (3 proxies)
 * W4:    Workspace, file system, bulk edits, clipboard, file events (5 proxies)
 * W5:    UI services — quickOpen, statusBar, output, progress, textEditors (5 proxies)
 * W7:    SCM (1 proxy)
 */

const commands = require("./mainThreadCommands")
const authentication = require("./mainThreadAuthentication")
const configuration = require("./mainThreadConfiguration")
const theming = require("./mainThreadTheming")
const errors = require("./mainThreadErrors")
const telemetry = require("./mainThreadTelemetry")
const extensionService = require("./mainThreadExtensionService")
const storage = require("./mainThreadStorage")
const secretState = require("./mainThreadSecretState")
const windowState = require("./mainThreadWindow")
const logService = require("./mainThreadLogService")
const localization = require("./mainThreadLocalization")
const messageService = require("./mainThreadMessageService")
const languageFeatures = require("./mainThreadLanguageFeatures")
const diagnostics = require("./mainThreadDiagnostics")
const documents = require("./mainThreadDocuments")
const workspace = require("./mainThreadWorkspace")
const fileSystem = require("./mainThreadFileSystem")
const bulkEdits = require("./mainThreadBulkEdits")
const clipboard = require("./mainThreadClipboard")
const fileSystemEvents = require("./mainThreadFileSystemEvents")
const quickOpen = require("./mainThreadQuickOpen")
const statusBar = require("./mainThreadStatusBar")
const outputService = require("./mainThreadOutputService")
const progress = require("./mainThreadProgress")
const textEditors = require("./mainThreadTextEditors")
const treeViews = require("./mainThreadTreeViews")
const scm = require("./mainThreadSCM")
const debugService = require("./mainThreadDebugService")
const search = require("./mainThreadSearch")
const testing = require("./mainThreadTesting")
const task = require("./mainThreadTask")
const profileContentHandlers = require("./mainThreadProfileContentHandlers")
const mcp = require("./mainThreadMcp")

function registerAllProxies(server, opts = {}) {
  if (!server || typeof server.onRpc !== "function") {
    console.error("[main-thread] Invalid server — skipping proxy registration")
    return
  }

  commands.register(server, opts)
  authentication.register(server, opts)
  configuration.register(server, opts)
  theming.register(server, opts)
  errors.register(server, opts)
  telemetry.register(server, opts)
  extensionService.register(server, opts)
  secretState.register(server, opts)
  storage.register(server, opts)
  windowState.register(server, opts)
  logService.register(server, opts)
  localization.register(server, opts)
  debugService.register(server, opts)
  messageService.register(server, opts)
  languageFeatures.register(server, opts)
  diagnostics.register(server, opts)
  documents.register(server, opts)
  workspace.register(server, opts)
  fileSystem.register(server, opts)
  bulkEdits.register(server, opts)
  clipboard.register(server, opts)
  fileSystemEvents.register(server, opts)
  quickOpen.register(server, opts)
  statusBar.register(server, opts)
  outputService.register(server, opts)
  progress.register(server, opts)
  textEditors.register(server, opts)
  treeViews.register(server, opts)
  scm.register(server, opts)
  search.register(server, opts)
  task.register(server, opts)
  testing.register(server, opts)
  profileContentHandlers.register(server, opts)
  mcp.register(server, opts)

  console.log("[main-thread] 33 MainThread proxies registered")
}

module.exports = { registerAllProxies }
