export type MigrationReuseLevel = "direct" | "adapter" | "protocol" | "defer"

export interface SourceMirrorMigrationItem {
  id: string
  title: string
  ax: string
  level: MigrationReuseLevel
  sourcePaths: string[]
  targetArea: string
  reason: string
}

export const VSCODE_SOURCE_REFERENCE = "VS Code source reference is copied or adapted into D:\\Workspace before packaging"

export const sourceMirrorMigrationItems: SourceMirrorMigrationItem[] = [
  {
    id: "vendor-vscode-mirror",
    title: "自包含 VS Code vendor 镜像",
    ax: "AX-MIGRATION",
    level: "adapter",
    sourcePaths: [
      "src/vs/base",
      "src/vs/platform",
      "src/vs/workbench",
      "extensions",
    ],
    targetArea: "vendor/vscode + scripts/build-ext-host.js + scripts/import-vscode-extensions.js",
    reason: "迁移提速不再靠零散摘函数；先把需要的 VS Code 源码闭包复制到 Codek 内部 vendor 镜像，外部 VS Code checkout 只作为同步来源，运行、构建和打包不能依赖外部工作区。",
  },
  {
    id: "vscode-platform-shims",
    title: "VS Code Platform Shim 层",
    ax: "AX-MIGRATION",
    level: "adapter",
    sourcePaths: [
      "src/vs/nls.ts",
      "src/vs/platform/product/common/productService.ts",
      "src/vs/platform/environment/common/environment.ts",
      "src/vs/platform/log/common/log.ts",
      "src/vs/platform/instantiation/common",
      "src/vs/platform/configuration/common",
      "src/vs/platform/files/common",
    ],
    targetArea: "frontend/vite-project/src/vscode-adapter + desktop/services/*Adapter.js",
    reason: "VS Code 源码慢在服务图而不是函数体；先补 nls/product/environment/log/configuration/file/instantiation 等 shim，后续大模块能少改源码接入 Codek。",
  },
  {
    id: "file-service",
    title: "FileService DI / Provider IO / Watcher",
    ax: "AX-MIGRATION",
    level: "adapter",
    sourcePaths: [
      "src/vs/platform/files/common/files.ts",
      "src/vs/platform/files/common/fileService.ts",
      "src/vs/platform/files/node/diskFileSystemProvider.ts",
      "src/vs/platform/files/node/watcher",
      "src/vs/platform/files/electron-main/diskFileSystemProvider.ts",
      "src/vs/workbench/services/files/common/files.ts",
      "src/vs/workbench/services/workingCopy/common/workingCopyFileService.ts",
    ],
    targetArea: "frontend/vite-project/src/vscode-adapter/platform/files/common/files.ts + frontend/vite-project/src/vscode-adapter/workbench/services/textfile/common/textFileService.ts + frontend/vite-project/src/workspace/manager.js + MCP resource provider-backed FileService",
    reason: "FileService 是 Explorer、Search、TextFile/WorkingCopy、SCM 和 Agent evidence 的共同文件改动观察底座；迁移必须在现有 provider registry 上原位补 IFileService service brand、provider open/read/write/close、CancellationToken、write cancellation、onDidFailOperation failure evidence、FileOperationError metadata、watch/error forwarding、watch request 去重/refcount、provider watcher coalescing、watcher create/change/delete ordering、recursive/non-recursive filtering、internalOnDidFilesChange 与全局 onDidFilesChange 分流、createWatcher()/IFileSystemWatcher correlation-specific event routing、provider-backed desktop watcher event/dispose bridge、workspace file-operation failed evidence、copy_entry failure evidence 和 Codek workspace IPC provider 句柄语义，不新增第二套 FileService/workspace 状态源。",
  },
  {
    id: "textfile-working-copy-hot-exit-evidence",
    title: "TextFile / WorkingCopy Hot Exit Evidence",
    ax: "AX-MIGRATION",
    level: "adapter",
    sourcePaths: [
      "src/vs/workbench/services/textfile/browser/textFileService.ts",
      "src/vs/workbench/services/textfile/common/textfiles.ts",
      "src/vs/workbench/services/workingCopy/common/workingCopyService.ts",
      "src/vs/workbench/services/workingCopy/common/workingCopyBackupService.ts",
      "src/vs/workbench/services/workingCopy/common/workingCopyBackup.ts",
      "src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts",
      "src/vs/workbench/services/workingCopy/common/workingCopyFileService.ts",
    ],
    targetArea: "frontend/vite-project/src/vscode-adapter/workbench/services/textfile/common/textFileService.ts + frontend/vite-project/src/vscode-adapter/workbench/services/workingCopy/common/{workingCopyService,workingCopyFileService,storedFileWorkingCopy}.ts + frontend/vite-project/src/workspace/manager.js + frontend/vite-project/src/App.vue smoke bridge + desktop/main.js smoke report + scripts/electron-ui-smoke.js + .codek/reports/working-copy-hot-exit-latest-result.json",
    reason: "Hot-exit evidence 必须从唯一 workspace.manager WorkingCopy 状态源派生 dirty、backup artifact、close guard、restore attempt、workspaceRoot、risk 和 evidencePath；adapter 层已补 ITextFileService / IWorkingCopyService / IWorkingCopyFileService / IWorkingCopyBackupService service brand、ServiceCollection 解析、singleton registration 和全局 service 兼容实例，旧 open/save/reload/backup/restore/retention helper 继续代理同一 TextFile/WorkingCopy model。Native shutdown lifecycle 对照 VS Code Workbench lifecycle/shutdown veto 模型接入 Electron close/before-quit/will-prevent-unload 与 renderer beforeunload bridge：dirty close 会先备份同一 WorkingCopy 状态，smoke 覆盖 cancel/confirm/force、backup retained after cancel、save-to-disk clears dirty、revert-from-disk clears dirty，并写 JSON/Markdown evidence；renderer unavailable 仅作为保守降级 risk 记录，不新增第二套 hot-exit/global evidence store。",
  },
  {
    id: "large-file-real-project-ui-evidence",
    title: "Large File Real Project UI Evidence",
    ax: "AX-MIGRATION",
    level: "adapter",
    sourcePaths: [
      "src/vs/editor/common/model/textModel.ts",
      "src/vs/editor/browser",
      "src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts",
      "src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts",
    ],
    targetArea: "frontend/vite-project/src/App.vue real-project-ui large-file smoke bridge + frontend/vite-project/src/workspace/manager.js byte-window range state + scripts/workbench-large-file-256mb-smoke.js + scripts/workbench-large-file-256mb-smoke.test.js + desktop/main.js real-project-ui acceptance/Markdown",
    reason: "Real-project large-file evidence 必须证明真实 Electron 工作台里大文件内容可见、显式 next-window 深视口可见、用户 PageDown/scroll-bottom/scrollbar drag/End 后视口不空白、final window 和 close/reopen 仍可见。Codek 对照 VS Code TextModel heap-operation guard 和 file editor large-file 保护语义，继续走 workspace.manager byte-window/range state，不恢复 full-content 读取；real-project-ui 默认 fixture 提升到 128MiB，先验证首窗口 next-window，再执行用户滚动，再验证最终窗口，避免 64MiB 两窗口 fixture 先滚到底后把 next-window/direct-load 误判为失败。scrollbar drag 只有在 drag 前仍有下一窗口时才要求 direct-loaded；如果已处于 final/single-window，则必须继续要求 drag dispatched、scroll advanced、offset advanced、viewport text visible 和 End viewport visible，不放宽真实可见性。旧 large-file smoke 脚本导出 report gate collector 并用 node:test 锁住 direct-load-required contract，旧 FileService/SearchService/TextFile 主链路不重写，不新增第二套大文件状态源。manualAcceptanceContract / manual-real-ui 11 scenarios 把本阶段人工复验固化为快速滚动、深窗口跳转、close/reopen、同目录 Cursor/Codek 对照和普通 sibling 文件切换，自动化 pass 只能预填客观 evidence，不能替代用户手感确认。",
  },
  {
    id: "editor-marker-problems-service",
    title: "Editor / MarkerService / Problems Surface",
    ax: "AX-MIGRATION",
    level: "adapter",
    sourcePaths: [
      "src/vs/platform/markers/common/markers.ts",
      "src/vs/platform/markers/common/markerService.ts",
      "src/vs/workbench/contrib/markers/browser/markersModel.ts",
      "src/vs/workbench/contrib/markers/browser/markersView.ts",
      "src/vs/workbench/services/editor/common/editorService.ts",
      "src/vs/editor/common/model/textModel.ts",
    ],
    targetArea: "frontend/vite-project/src/vscode-adapter/platform/markers/common/markers.ts + frontend/vite-project/src/components/problemState.ts + frontend/vite-project/src/workbench/editorDiagnosticsLifecycle.ts + frontend/vite-project/src/vscode-adapter/workbench/contrib/markers/browser/markersViewModel.ts + frontend/vite-project/src/components/ProblemsPanel.vue",
    reason: "Editor diagnostics 必须从 Monaco model marker 进入 VS Code-style `IMarkerService` / `MarkerService`，再投影到 Problems surface；2026-06-24 已补 markerService service identifier、`_serviceBrand`、singleton registration、ServiceCollection 解析、owner/resource keyed marker store、`onMarkerChanged` lifecycle、statistics、changeOne/changeAll/remove/read 和 Windows path/URI 覆盖。`problemState` 保留旧 API 给 AI scan、lint、LSP、compiler 和 ProblemsPanel 调用，但内部改为 `globalMarkerService` 的兼容投影层，reactive diagnostics 引用不变，`diagnosticSources` / sourceDiags 只从 marker service 重建，不再作为第二套事实源。`installEditorMarkerSync()` 直接用 owner `monaco` 写入 marker service，ProblemsPanel 继续通过 markersViewModel 做 severity/source/file grouping 和点击 openFile range；回归 smoke 已覆盖 Monaco marker event -> `globalMarkerService` -> `problemState(globalMarkerService)` -> markers view model -> `buildProblemsWorkbenchSnapshot()` -> `workbench.actions.view.toggleProblems`，证明 Problems 数据源、视图模型和命令入口未漂移。不重写 EditorPart/FileService/TextFile/WorkingCopy/large-file 主路径，也不新增第二套 diagnostics/problems 状态源。",
  },
  {
    id: "search-service",
    title: "SearchService DI / onSearch Activation",
    ax: "AX-MIGRATION",
    level: "adapter",
    sourcePaths: [
      "src/vs/workbench/services/search/common/search.ts",
      "src/vs/workbench/services/search/common/searchService.ts",
      "src/vs/workbench/services/search/common/queryBuilder.ts",
      "src/vs/workbench/services/search/common/searchExtTypes.ts",
      "src/vs/workbench/services/search/browser/searchService.ts",
      "src/vs/workbench/contrib/search/browser/searchView.ts",
      "src/vs/workbench/contrib/search/browser/searchActionsBase.ts",
      "src/vs/workbench/contrib/search/browser/searchActionsFind.ts",
      "src/vs/workbench/contrib/search/browser/searchActionsNav.ts",
      "src/vs/workbench/contrib/search/browser/searchActionsTopBar.ts",
      "src/vs/workbench/contrib/search/browser/searchTreeModel/searchModel.ts",
    ],
    targetArea: "frontend/vite-project/src/vscode-adapter/workbench/services/search/common/searchService.ts + desktop/services/search/{index,searchServiceAdapter}.js + desktop/services/extensions-host/mainThread/mainThreadSearch.js",
    reason: "SearchService 是 Search view、Quick Open、Agent evidence workspace search 和后续 SCM/Testing/Timeline 的读取底座；迁移应补 ISearchService service brand、ServiceCollection 解析、provider registration、query normalization、CancellationToken、progress forwarding、SearchError/limit/stale result mapping、multi-scheme fanout、unsupported provider 边界、provider lifecycle / clearCache 去重和 onSearch:* activation，并继续复用现有 desktop provider registry/raw search/workspace search；后端 workspace search 也必须按 folder scheme 激活/查询 provider，非 file scheme 缺 provider 时返回 success=false、partial 和 providerFailures，禁止落入本地 file fallback 假成功；SearchPanel 只能经同一 adapter service 代理到 Electron/HTTP transport，不新增第二套搜索状态源。",
  },
  {
    id: "bulk-edit-replace",
    title: "BulkEdit / ReplaceService",
    ax: "AX-MIGRATION",
    level: "adapter",
    sourcePaths: [
      "src/vs/editor/browser/services/bulkEditService.ts",
      "src/vs/workbench/contrib/bulkEdit/browser/bulkEditService.ts",
      "src/vs/workbench/contrib/search/browser/replaceService.ts",
    ],
    targetArea: "frontend/vite-project/src/vscode-adapter/workbench/services/bulkEdit/common/bulkEditService.ts + frontend/vite-project/src/vscode-adapter/workbench/contrib/search/browser/replaceService.ts + frontend/vite-project/src/workbench/searchFileActions.ts + frontend/vite-project/src/App.vue search-replace smoke bridge + desktop/main.js workbench-search-replace evidence + desktop/services/extensions-host/mainThread/mainThreadBulkEdits.js",
    reason: "Search Replace 必须从直接 content.replace 收束到 VS Code-style ReplaceService -> IBulkEditService -> Codek workspace save path，支持 dry-run、风险摘要、失败/跳过摘要、resource/range/match/operation/reason/rollbackRisk failure evidence、partial failure 资源列表和可回滚说明；真实 search-replace smoke 必须先 dry-run preview 证明不写盘，再通过同一 ReplaceService/BulkEdit 边界 apply replace one/all，并写 workbench-search-replace JSON/Markdown evidence、affected resources、rollback risk、searchRefreshEvidence 和 watcherRefreshStable，证明 FileService watcher/coalescing 后 Search 结果刷新稳定且 changed files 不残留旧 needle 命中；extension-host WorkspaceEdit 兼容层也必须报告 changedResources / rollbackRisk，避免 partial success 静默，同时保留 TextFile/WorkingCopy/FileService/Agent evidence 的工作区改动可观察边界。",
  },
  {
    id: "vscode-dependency-closure-importer",
    title: "依赖闭包复制与 import 重写脚本",
    ax: "AX-MIGRATION",
    level: "adapter",
    sourcePaths: [
      "src/vs",
      "extensions",
    ],
    targetArea: "scripts/vscode-dependency-closure-importer.js + vendor/vscode + frontend/vite-project/src/vscode-adapter/generated/vscode",
    reason: "新增迁移优先用脚本按 entrypoint 解析 src/vs import 闭包、复制到 Codek 内部、重写别名并输出缺失 shim 清单；默认源必须是仓库内 vendor/vscode，只有显式 --refresh-vendor --src 才允许读取外部 VS Code checkout，避免每个线程继续手工复制粘贴或形成运行时外部源码依赖。2026-06-24 已实体化最小闭包样例：从外部 VS Code checkout 只读刷新 src/vs/base/common/lifecycle.ts 与 src/vs/base/common/uri.ts 到 vendor/vscode，再从仓内 vendor 生成 frontend/vite-project/src/vscode-adapter/generated/vscode；闭包 68 个源码文件、266 条 import edges，generated import 已重写为相对路径，缺失 shim 清单仅剩 observableInternal/logging/debugger/devToolsLogger.ts -> ./debuggerApi.js（VS Code 源只有 debuggerApi.d.ts，暂不纳入运行时闭包）。",
  },
  {
    id: "module-batch-migration",
    title: "按大模块批量迁移",
    ax: "AX-MIGRATION",
    level: "adapter",
    sourcePaths: [
      "src/vs/workbench/services",
      "src/vs/workbench/contrib",
      "src/vs/platform",
    ],
    targetArea: "vscode-adapter + desktop/services + workbench integration",
    reason: "后续优先按 base/platform/workbench service/contrib/extension host 模块推进；每批要求接入调用方、旁路旧逻辑、focused tests、typecheck、source boundary gate，而不是只搬单个工具函数。",
  },
  {
    id: "extension-marketplace-workbench-service",
    title: "Extension Marketplace Workbench Service / Gallery Surface",
    ax: "AX4",
    level: "adapter",
    sourcePaths: [
      "src/vs/platform/extensionManagement/common/extensionGalleryService.ts",
      "src/vs/platform/extensionManagement/common/extensionManagement.ts",
      "src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts",
      "src/vs/workbench/contrib/extensions/browser/extensionsActions.ts",
      "src/vs/workbench/contrib/extensions/browser/extensionEditor.ts",
      "src/vs/workbench/contrib/extensions/browser/extensionsQuickAccess.ts",
      "src/vs/workbench/contrib/extensions/browser/extensionsViewlet.ts",
    ],
    targetArea: "frontend/vite-project/src/extensions/extensionsWorkbenchService.ts + frontend/vite-project/src/extensions/workbenchContributions.ts + frontend/vite-project/src/components/Marketplace.vue + frontend/vite-project/src/components/ExtensionDetails.vue + frontend/vite-project/src/App.vue + desktop/main.js",
    reason: "Extension Marketplace 需要从组件内散调用收束到 VS Code-style IExtensionsWorkbenchService、Action2/Menu/View、QuickAccess、enable/disable 和 editor view model；实现必须继续复用现有 ehClient、cache-first/targetPlatform/download cancellation/install plan/progress/audit/trust gate，并通过 evidence summary / getSurfaceSnapshot() 暴露 installState、progress、rollback risk、local-first、workbench.view.extensions、workbench.extensions.marketplace、ext QuickAccess 和 no-second-state 约束；Marketplace.vue、ExtensionDetails.vue、App.vue 和 real-project-ui smoke 必须代理同一 service surface，不新增第二套扩展安装状态源。",
  },
  {
    id: "extension-trust-remote-auth-workbench",
    title: "Extension Host / Workspace Trust / Remote Authority / Authentication Workbench Contribution",
    ax: "AX4",
    level: "adapter",
    sourcePaths: [
      "src/vs/workbench/services/extensions/common/extensions.ts",
      "src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts",
      "src/vs/platform/workspace/common/workspaceTrust.ts",
      "src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts",
      "src/vs/platform/remote/common/remoteAuthorityResolver.ts",
      "src/vs/workbench/services/authentication/common/authentication.ts",
      "src/vs/workbench/contrib/authentication/browser/authentication.contribution.ts",
      "src/vs/platform/actions/common/actions.ts",
      "src/vs/platform/commands/common/commands.ts",
      "src/vs/workbench/common/views.ts",
    ],
    targetArea: "frontend/vite-project/src/workbench/extensionTrustRemoteAuthWorkbench.ts + frontend/vite-project/src/App.vue + desktop/main.js + desktop/services/smoke/realProjectUiGateAttribution.js",
    reason: "Extension Host、Workspace Trust、Remote Authority 和 Authentication 的入口先收束到 VS Code-style service facade、_serviceBrand、registerSingleton、ServiceCollection、Action2/Menu/View contribution 和 real-project-ui evidence，而不是实现完整 VS Code extension host runtime、完整远端账号体系或 OAuth provider。`IExtensionHostService` 只代理现有 `extensionsWorkbenchService` / `ehClient` 激活占位 evidence，`IWorkspaceTrustManagementService` 只代理现有 workspace trust routes + agentPolicy gate，`IRemoteAuthorityResolverService` 只代理 `remoteManager` 并增加 resolver success/failure/cache evidence，`IAuthenticationService` 只代理 `authState` + MCP OAuth session 边界且不保存 token。`App.vue` 在 remote view 投影 `codek.view.extensionTrustRemoteAuth` 四个 surface，real-project-ui smoke seed activation/trust allow-deny/remote resolve-cache-failure/auth missing-pending-authorized-expired-revoked-error，`desktop/main.js` 和 gate attribution 以 6 个 acceptance 验证 service boundary、command ids、UI surface 和 evidence；旧 MCP OAuth、Gallery、Agent evidence、settings/status UI 都继续代理同一状态源，不新增第二套 extension/trust/remote/auth store。manualAcceptanceContract 把 trust allow/deny、remote resolve success/failure/cache、auth missing/pending/authorized/expired/revoked/error 和 token redaction 写入人工 replay steps，blocked/pass 必须可归属到 Trust、Remote Authority、Authentication 或 Extension Host。",
  },
  {
    id: "mcp-quickaccess-gallery-workbench-surface",
    title: "MCP / QuickInput / Gallery View-Action-DI Surface",
    ax: "AX4",
    level: "adapter",
    sourcePaths: [
      "src/vs/platform/quickinput/common/quickInput.ts",
      "src/vs/platform/quickinput/browser/quickInput.ts",
      "src/vs/workbench/services/quickinput/browser/quickInputService.ts",
      "src/vs/workbench/browser/quickaccess.ts",
      "src/vs/workbench/contrib/quickaccess/browser/quickAccess.contribution.ts",
      "src/vs/workbench/contrib/mcp/browser/mcpResourceQuickAccess.ts",
      "src/vs/workbench/contrib/mcp/browser/mcpServerEditor.ts",
      "src/vs/workbench/contrib/mcp/browser/mcpServerActions.ts",
      "src/vs/platform/mcp/common/mcpGalleryService.ts",
      "src/vs/workbench/common/views.ts",
    ],
    targetArea: "frontend/vite-project/src/workbench/mcpCommands.ts + frontend/vite-project/src/workbench/mcpResourceAccess.ts + frontend/vite-project/src/vscode-adapter/platform/quickinput/common/quickAccess.ts + frontend/vite-project/src/workbench/workbenchLayoutModel.ts + frontend/vite-project/src/workbench/workbenchLayoutActions.ts + frontend/vite-project/src/components/QuickPickDialog.vue + frontend/vite-project/src/App.vue + desktop/main.js + scripts/electron-ui-smoke.js",
    reason: "MCP resource/provider、Gallery detail editor/action、view title menu 和 QuickAccess 必须共享现有 mcpCommands、provider-backed FileService、QuickInput/QuickAccess 和 registry client；QuickInput service alias 需要支持 showQuickPick/showInputBox 与 AbortSignal cancellation，QuickPickDialog 必须暴露 data-codek-smoke=\"quick-input-workbench\" 与 quickPick/inputBox kind，让 real-project-ui smoke 通过同一 quickInputService 打开真实 dialog、完成 quick pick accept 和 input box Escape cancel，并把 quickInputWorkbenchRealUi / quickInputWorkbenchServiceBoundary 写入 desktop acceptance/Markdown。MCP surface 新增 VS Code-style `IMcpWorkbenchService` / `_serviceBrand` / `registerSingleton` / `ServiceCollection` 解析，`getMcpWorkbenchSurfaceSnapshot()` 只代理 `getMcpResourceAccessEvidenceSummary()` 和 Gallery detail model；MCP resource/Gallery detail 通过 evidence summary 暴露只读 provider path、metadata、action constraints、`mcpGalleryWorkbenchDetailActionEvidence`、`mcpWorkbenchPreservesAgentApproval` 和 `mcpWorkbenchNoSecondState`，不重写 transport、不绕过 Gateway/OAuth、安全审批、Agent evidence 或 missing input prompt。Workbench surface 继续把 `workbench.view.mcp` 映射到同一 layout/view command 与 sidebar state，`App.vue` 只投影 service snapshot metadata，不展示 resource content；real-project-ui smoke 通过 open-mcp / mcp-workbench-surface 证明 MCP servers/resources/gallery surface 可见，并由 desktop/main.js 将 mcpWorkbenchSurfaceVisible / mcpWorkbenchServiceBoundary / mcpGalleryWorkbenchDetailActionEvidence 纳入 acceptance/Markdown evidence，不新增第二套 MCP 或 QuickInput 状态源。",
  },
  {
    id: "agent-evidence-workbench",
    title: "可验收 Agent 工程工作台",
    ax: "AX-PRODUCT",
    level: "adapter",
    sourcePaths: [
      "src/vs/workbench/contrib/testing",
      "src/vs/workbench/contrib/scm",
      "src/vs/workbench/contrib/timeline",
      "src/vs/workbench/services/progress",
      "src/vs/workbench/services/notification",
      "src/vs/platform/notification/common/notification.ts",
      "src/vs/workbench/common/views.ts",
      "src/vs/platform/actions/common/actions.ts",
      "src/vs/platform/commands/common/commands.ts",
    ],
    targetArea: "frontend/vite-project/src/workbench/agentEvidenceWorkbench.ts + frontend/vite-project/src/App.vue + frontend/vite-project/src/agent/orchestratorClient.ts + desktop/services/agentLoop/releaseEvidenceExport.js + desktop/main.js real-project-ui smoke + workbench layout/view/menu/command registry + Agent Evidence SCM/Testing/Timeline/Progress/Notification facade services + Agent Evidence Action2/SCMTitle/TestItem/ViewTitle contribution + Agent Evidence unified list/detail/filter/export surface + .codek/reports",
    reason: "Codek 差异化不是拼通用聊天，而是把 Agent 计划、执行、测试、失败、真实 UI 验收、工作区 diff、审批和回滚风险做成可追责证据链；迁移 VS Code SCM/Testing/Timeline/Progress/Notification surface 时必须从 release evidence 派生统一 report contract，包含 source/timestamp/workspace/commands/artifacts/failure causes/next actions/correlation id/lifecycle 元数据，并通过 IAgentEvidenceWorkbenchService service brand、子 surface service identifier（IAgentEvidenceScmService / IAgentEvidenceTestingService / IAgentEvidenceTimelineService / IAgentEvidenceProgressService / IAgentEvidenceNotificationService）、VS Code 原名 service identifier（ITimelineService='timeline' / ISCMService='scm' / ITestService='testService' / IProgressService='progressService' / INotificationService='notificationService'）、App.vue sidebar pane、Activity Bar/View/Menu/Command context 和 Electron real-project-ui smoke 暴露 SCM/Testing/Timeline/Progress/Notification 关键字段；本阶段继续加厚 VS Code-style 可操作 contract：SCM resource open/diff/stage/attach command metadata、Testing rerun command/failure detail/resource links、Timeline command/resource/link、Progress aggregate status/cancel command/aria label、Notification dedupe key/dismiss command/focus target 都从同一 report/surface 派生并进入 real-project-ui metrics 和 Markdown report；进一步把这些字段提升为 facade service method contract：getScmRepositories()/getScmResourceGroups()/getScmResourceActions()/openScmResource()/diffScmResource()/stageScmResource()、getTestingRunSummary()/getTestResults()/rerunTests()、getTimelineItem()/getTimelineItemCommand()/getTimelineItemResource()、getProgressAggregate()/cancelProgress()、getNotificationSeverityCounts()/getNotificationActions()/dismissNotification() 均只读代理同一 IAgentEvidenceWorkbenchService.getSurface()，其中 agent.evidence.stageResource 只作为 read-only evidence action，不写 Git index；统一 evidence list/detail/filter/export 由同一 workbench surface 派生，IAgentEvidenceWorkbenchService.getEvidenceItems()/getEvidenceDetail()/getExportDescriptor()、agent.evidence.openDetail、agent.evidence.exportJson、agent.evidence.exportMarkdown、App.vue data-agent-evidence-list/detail/editor/export DOM、desktop agentEvidenceWorkbenchListDetailExport acceptance 和 release Markdown Evidence List/Detail/Export 表必须共享同一 report/surface；子 service facade 只代理同一 workbench surface，VS Code 原名 service id 也解析到同一个 facade；2026-06-24 继续把 contribution registration 收束到 Action2/registerAction2，CommandPalette/F1、ViewTitle、SCMTitle、TestItem、AgentEvidenceTimeline 菜单都从同一 service surface 派生，`getContributionSummary()` 暴露 service id、VS Code service ids、view containers、view ids、command/action ids、menu ids 和 no-second-state 约束；`AGENT_EVIDENCE_SURFACE_BRIDGE_AUDIT` 逐项固定 SCM/Timeline/Testing/Notifications/Progress 的 VS Code 源路径、Codek state source、service id、view id、command/menu、DOM smoke selector、real-project-ui metric key 和仍需人工 UI 验收缺口，防止只在文档里声称存在。不新增第二套 evidence/progress/notification/SCM/testing/timeline 状态源，并服务这个闭环。manualAcceptanceContract 同步记录 SCM/Testing/Timeline/Notification Center/Progress 人工复验步骤、failure owner、manualStatus 和报告路径，确保自动化 evidence list/detail/export pass 不被误标为完整人工体验通过。",
  },
  {
    id: "terminal-debug-output-task-problems-workbench",
    title: "Terminal / Debug / Output / Task / Problems Workbench Contribution",
    ax: "AX-WORKBENCH-PANEL",
    level: "adapter",
    sourcePaths: [
      "src/vs/workbench/contrib/terminal/browser/terminal.ts",
      "src/vs/workbench/services/output/common/output.ts",
      "src/vs/workbench/contrib/debug/common/debug.ts",
      "src/vs/workbench/contrib/tasks/common/taskService.ts",
      "src/vs/workbench/contrib/markers/common/markers.ts",
      "src/vs/workbench/services/panecomposite/browser/panecomposite.ts",
      "src/vs/workbench/browser/parts/panel",
    ],
    targetArea: "frontend/vite-project/src/workbench/terminalDebugTaskWorkbench.ts + frontend/vite-project/src/components/TaskWorkbenchPanel.vue + frontend/vite-project/src/App.vue + desktop/main.js + desktop/services/smoke/realProjectUiGateAttribution.js",
    reason: "Terminal、Output、Debug、Task 和 Problems 的入口要先收束到 VS Code-style contribution registration、view container、Action2/Menu、CommandPalette 和 service identifier，而不是重写完整 terminal emulator 或 debug runtime。`terminalDebugTaskWorkbench.ts` 新增 `ITerminalService` / `IOutputService` / `IDebugService` / `ITaskService` / `IProblemsWorkbenchService` / `IPaneCompositePartService` / `ITerminalDebugTaskWorkbenchService` 的 `_serviceBrand`、singleton registration 和 ServiceCollection 解析；facade 只代理现有 `terminalManager`、`outputLogTelemetryService`、Debug 的 `debugState`、Task 的 `taskConfigurationModel/userTasksService/problemMatcherRegistry`、`taskRunner/TaskSystemLifecycleProjection` 和 `problemsDiagnosticsService(globalMarkerService)`。`App.vue` bridge 只把 Terminal/Output 映射到既有 bottom panel，把 Debug 映射到现有 sidebar view，把 Tasks 映射到 `TaskWorkbenchPanel.vue` bottom panel surface，把 Problems 映射到只读 ProblemsPanel open/toggle，不写 diagnostics/markers/problems 主状态；旧 View 菜单和 Command Palette 的 Output/Problems 入口优先代理到 `workbench.action.output.showOutput` / `workbench.actions.view.toggleProblems` contribution commands，未注册时才回退旧面板函数；real-project-ui smoke 执行 `workbench.action.terminal.*`、`workbench.action.output.showOutput`、`workbench.action.debug.*`、`workbench.action.tasks.*`、`workbench.actions.view.toggleProblems` 并写 `terminalDebugTaskWorkbench*` metrics / `taskWorkbenchPanelSurface`。`desktop/main.js` 和 `realProjectUiGateAttribution` 将 service boundary、panel bridge、output channel、task run、Task panel surface、debug session、terminal command 和 Problems read-only bridge 作为 8 个独立 acceptance，保留 Agent evidence/progress/notification、中文化、安全审批和工作区改动可观察能力，不新增第二套 terminal/output/debug/task/problems 状态源。manualAcceptanceContract 要求人工从真实 Workbench controls 或 Command Palette 复验 Terminal/Output/Debug/Tasks/Problems 可见、action 可触发且失败归属清晰。",
  },
  {
    id: "code-oss-fork-spike",
    title: "Code-OSS Workbench 尖刺实验",
    ax: "AX-SPIKE",
    level: "defer",
    sourcePaths: [
      "src/vs/workbench/browser",
      "src/vs/workbench/electron-sandbox",
      "src/vs/platform/instantiation",
      "src/vs/workbench/services/views",
      "src/vs/workbench/services/extensions",
    ],
    targetArea: "isolated branch/worktree only",
    reason: "只用 3-5 天验证更像 Cursor 的 Code-OSS fork 路线：能启动 Workbench、挂 Codek Agent 侧栏、读写当前 workspace、显示任务证据链。未通过四项前不得替换 M1 主线，也不得废弃现有 MCP/QuickInput/WorkingCopy/Settings 等成果。",
  },
  {
    id: "contextkeys",
    title: "Context Key 表达式",
    ax: "AX3",
    level: "direct",
    sourcePaths: [
      "src/vs/platform/contextkey/common/scanner.ts",
      "src/vs/platform/contextkey/common/contextkey.ts",
    ],
    targetArea: "frontend/vite-project/src/vscode-adapter/platform/contextkey/common/contextkey.ts + frontend/vite-project/src/workbench/contextKeys.ts",
    reason: "纯逻辑解析器，适合直接迁移为 Codek 命令、菜单、快捷键、视图共享的 when clause 底座；2026-06-24 已补 IContextKeyService service identifier、_serviceBrand、singleton registration 和 ServiceCollection 解析，globalContextKeyService 仍是唯一 context key 状态源。",
  },
  {
    id: "keybinding-resolver",
    title: "Keybinding Resolver",
    ax: "AX3",
    level: "direct",
    sourcePaths: [
      "src/vs/platform/keybinding/common/keybindingResolver.ts",
      "src/vs/platform/keybinding/common/keybindingsRegistry.ts",
      "src/vs/platform/keybinding/common/resolvedKeybindingItem.ts",
    ],
    targetArea: "frontend/vite-project/src/keybindings.ts",
    reason: "快捷键冲突解析和 when clause 判定可沿用 VS Code 心智，避免继续维护简化版；2026-06-24 已补 IKeybindingService service identifier、_serviceBrand、singleton registration 和 ServiceCollection 解析，facade 只代理现有 registerKeybinding/registerCommandKeybinding/handleKeyEvent/getRegisteredKeybindings/setKeybindingContext，不新增第二套 keybinding 状态源。",
  },
  {
    id: "configuration-model",
    title: "Configuration Model",
    ax: "AX2",
    level: "adapter",
    sourcePaths: [
      "src/vs/platform/configuration/common/configurationModels.ts",
      "src/vs/platform/configuration/common/configurationRegistry.ts",
      "src/vs/platform/configuration/common/configurationService.ts",
      "src/vs/workbench/api/common/configurationExtensionPoint.ts",
      "src/vs/platform/theme/common/themeService.ts",
      "src/vs/platform/theme/common/iconRegistry.ts",
      "src/vs/workbench/services/themes/common/workbenchThemeService.ts",
      "src/vs/workbench/services/themes/common/themeConfiguration.ts",
    ],
    targetArea: "frontend/vite-project/src/settings + frontend/vite-project/src/vscode-adapter/platform/theme/common/themeService.ts + desktop/services/settings",
    reason: "配置合并规则可以复用，但需要接入 Codek settingsStore、中文 UI 和 workspace settings 文件；2026-06-24 已补 IConfigurationService 与 IWorkbenchConfigurationService service identifier、_serviceBrand、singleton registration 和 ServiceCollection 解析，workbenchConfigurationService 只代理同一个 SettingsStore 的 get/inspect/updateValue/onDidChangeConfiguration。2026-06-25 Settings/Profile/Theme/Icon 收口继续补 IThemeService / IWorkbenchThemeService service identifier、_serviceBrand、singleton registration、ServiceCollection 解析、onDidColorThemeChange/onDidFileIconThemeChange、inspectColorTheme/inspectFileIconTheme 和 setColorTheme/setFileIconTheme；Theme/Icon facade 只代理同一个 workbenchConfigurationService 的 workbench.colorTheme/workbench.iconTheme，profile 切换通过 SettingsStore 单次替换用户层后触发同一 service event，theme.ts 只消费 service event 投影 class/localStorage 兼容缓存，不新增第二套 theme/icon 状态源。",
  },
  {
    id: "commands",
    title: "Commands / Menu / Actions / Keybinding",
    ax: "AX1/AX3",
    level: "adapter",
    sourcePaths: [
      "src/vs/platform/commands/common/commands.ts",
      "src/vs/platform/actions/common/actions.ts",
      "src/vs/platform/keybinding/common/keybindingsRegistry.ts",
      "src/vs/platform/keybinding/common/keybindingResolver.ts",
      "src/vs/workbench/browser/actions.ts",
      "src/vs/workbench/browser/parts/editor/editorCommands.ts",
    ],
    targetArea: "frontend/vite-project/src/workbench/commandRegistry.ts + frontend/vite-project/src/vscode-adapter/platform/actions/common/menuRegistry.ts + frontend/vite-project/src/keybindings.ts + frontend/vite-project/src/components/{CommandPalette.vue,MenuBar.vue,menuModel.ts}",
    reason: "命令、Action2、MenuId/MenuRegistry 和 keybinding contribution 作为第二阶段 UI 重构控制面；必须原位接入 Codek 现有 CommandPalette/MenuBar/keybindings，不新增第二套状态源，并保留 Agent、中文化、证据链和安全审批入口。2026-06-24 已补 ICommandService service identifier、_serviceBrand、singleton registration 和 ServiceCollection 解析，CommandService 只代理现有 commandRegistry 执行与查询；Workbench Navigation / Command Palette / Keybinding 回归桥接把 extension command palette action、extension keybinding action 和 keybinding-only extension command backfill 收束到同一个 executeCommand()/commandRegistry，enablement 作为 precondition 执行，keybinding action 复用当前 keybinding context，并通过 duplicate command id stack smoke 证明后注册 VS Code-style facade 覆盖旧布局 fallback 且 dispose 后可回退旧路径。",
  },
  {
    id: "views",
    title: "View Registry / View Containers",
    ax: "AX1",
    level: "adapter",
    sourcePaths: [
      "src/vs/workbench/browser/layout.ts",
      "src/vs/workbench/browser/parts/activitybar/activitybarPart.ts",
      "src/vs/workbench/browser/parts/sidebar/sidebarPart.ts",
      "src/vs/workbench/browser/parts/editor/editorPart.ts",
      "src/vs/workbench/browser/parts/panel/panelPart.ts",
      "src/vs/workbench/browser/parts/titlebar/titlebarPart.ts",
      "src/vs/workbench/browser/parts/statusbar/statusbarPart.ts",
      "src/vs/workbench/browser/parts/statusbar/statusbarModel.ts",
      "src/vs/workbench/common/views.ts",
      "src/vs/workbench/services/views/common/viewsService.ts",
      "src/vs/workbench/services/layout/browser/layoutService.ts",
      "src/vs/workbench/services/editor/common/editorGroupsService.ts",
      "src/vs/platform/actions/common/actions.ts",
      "src/vs/platform/commands/common/commands.ts",
    ],
    targetArea: "frontend/vite-project/src/workbench/viewRegistry.ts + frontend/vite-project/src/workbench/workbenchLayoutModel.ts + frontend/vite-project/src/workbench/workbenchLayoutUiAdapter.ts + frontend/vite-project/src/workbench/workbenchLayoutActions.ts + frontend/vite-project/src/vscode-adapter/workbench/services/{layout,views,editor} + frontend/vite-project/src/App.vue + frontend/vite-project/src/components/MenuBar.vue + desktop/main.js real-project-ui workbench layout acceptance",
    reason: "View 容器心智需要对齐 VS Code；本阶段把 registry/layout snapshot 投影到真实 Vue Activity Bar、Sidebar、EditorPart、Panel、TitleBar、StatusBar 和 Command surface data-workbench DOM，并把 layout/view/action/command surface 挂到现有 commandRegistry/MenuRegistry/CommandPalette/MenuBar context。`IWorkbenchLayoutService` / `IViewsService` 只代理现有 workbenchLayoutModel 和 viewRegistry，补 service brand、ServiceCollection 解析、view contribution dispose 生命周期、Activity badge projection、openView/openViewContainer/closeViewContainer 可见性契约和 snapshot serialize/deserialize 持久化边界；本阶段继续把 `IWorkbenchLayoutService` 加厚为同一 snapshot 的 focus/size/neighbor/restore service contract，`hasFocus()`、`focusPart()`、`getSize()`、`getVisibleNeighborPart()` 不持有第二套状态，real-project-ui smoke 通过真实 DOM 聚焦 Sidebar/EditorPart/Panel 并采集 `workbenchLayoutServiceSizes`、`workbenchLayoutVisibleNeighbors`、`workbenchLayoutFocusPartIds`、`workbenchLayoutRestoreMatches`；`IEditorPartService` 作为轻量 EditorPart/EditorGroups facade 代理同一 editorGroups/tabLifecycle 状态，覆盖 open/close/focus/dirty/pin/reopen/move/split 与 overflow summary，并把 active editor、dirty/pinned/preview/overflow 暴露到 real-project-ui evidence；TitleBar/StatusBar/Command surface 继续由同一 `WorkbenchLayoutService.createSnapshot()` 投影 `titleBar`、`statusBar`、`commandSurface`，旧 snapshot hydrate 默认补齐这些 part，`App.vue` 暴露 `data-workbench-title-bar`、`data-workbench-status-bar`、`data-workbench-command-surface`，`desktop/main.js` 验收 `workbenchTitleBarSurfaceVisible`、`workbenchStatusBarSurfaceVisible`、`workbenchCommandSurfaceVisible` 和 `workbenchLayoutServiceFocusRestore`；Workbench Navigation 回归桥接已补 `workbench.view.settings` 真实命令入口，复用现有 openSettingsView()/Settings overlay，不再只有 registry placeholder；旧 Codek sidebar/editor/panel/status/title/menu helper 继续代理同一个 useWorkbenchLayout / open files / bottom panel / command menu registry 源驱动，Debug/Automation/Testing 暂以 registry placeholder 可观察入口保留，不新增第二套 UI 或 command/menu/layout 状态源。",
  },
  {
    id: "extension-points",
    title: "Extension Contribution Points",
    ax: "AX4",
    level: "protocol",
    sourcePaths: [
      "src/vs/workbench/services/extensions/common/extensionPoints.json",
      "src/vs/workbench/services/extensions/common/extensionsRegistry.ts",
      "src/vs/workbench/api/common/extHost*.ts",
      "src/vs/workbench/api/browser/mainThread*.ts",
    ],
    targetArea: "desktop/services/extensions-host",
    reason: "贡献点定义可复用，但完整 ExtHost/MainThread RPC 与 VS Code DI 强耦合，需要按协议逐步适配。",
  },
  {
    id: "theme-icons",
    title: "Theme / File Icon Theme",
    ax: "AX5",
    level: "adapter",
    sourcePaths: [
      "src/vs/platform/theme/common",
      "extensions/theme-seti",
      "extensions/theme-defaults",
    ],
    targetArea: "frontend/vite-project/src/theme.ts + components/FileIcon.vue",
    reason: "主题 registry 和默认主题资源可复用，需接入 Codek CSS variables 和文件树组件。",
  },
  {
    id: "tasks",
    title: "Tasks / Problem Matcher",
    ax: "AX8",
    level: "direct",
    sourcePaths: [
      "src/vs/workbench/contrib/tasks/common/problemMatcher.ts",
      "src/vs/workbench/contrib/tasks/common/problemCollectors.ts",
      "src/vs/workbench/contrib/tasks/common/taskConfiguration.ts",
    ],
    targetArea: "frontend/vite-project/src/workbench/taskDiscovery.ts",
    reason: "problem matcher 和 task config 解析大部分是纯逻辑，可优先迁移增强当前 tasks.json 支持。",
  },
  {
    id: "debug-terminal-scm",
    title: "Debug / Terminal / SCM 服务模型",
    ax: "AX9/AX10/AX11",
    level: "protocol",
    sourcePaths: [
      "src/vs/workbench/contrib/debug/common",
      "src/vs/workbench/contrib/terminal/common",
      "src/vs/workbench/contrib/scm/common",
    ],
    targetArea: "frontend/vite-project/src/debug + terminal + components/GitPanel.vue",
    reason: "模型和 schema 可复用，但真实运行依赖 Codek 的 node-pty、debug service、simple-git 和 Agent 审批。",
  },
]

export function getMigrationItemsByLevel(level: MigrationReuseLevel): SourceMirrorMigrationItem[] {
  return sourceMirrorMigrationItems.filter((item) => item.level === level)
}

export function getMigrationItem(id: string): SourceMirrorMigrationItem | null {
  return sourceMirrorMigrationItems.find((item) => item.id === id) || null
}
