import type { PluginManifest, PluginEngineTopLevel, PluginPostfixTemplate, PluginEngineClass } from "../types"

export const javaPluginManifest: PluginManifest = {
  id: "codek-java-intellisense",
  name: "codek-java",
  displayName: "Java IntelliSense",
  version: "2.1.0",
  publisher: "Codek Team",
  description: "IDEA-level Java code completion with JDK version-aware API suggestions.",
  icon: "JV",
  license: "MIT",
  keywords: ["java", "intellisense", "completion", "jdk", "standard-library"],
  categories: ["languages"],
  language: "java",
  jdkVersionMin: "8",
  engines: { codek: "*" },
  activationEvents: ["onLanguage:java"],
  extensionDependencies: [],
  contributes: { languages: [{ id: "java", aliases: ["Java"], extensions: [".java", ".jav"] }], snippets: {} },
  snippets: [],
  preview: false,
  size: 42 * 1024,
  engineConfig: {
    keywords: [
      "abstract", "assert", "boolean", "break", "byte", "case", "catch",
      "char", "class", "continue", "default", "do", "double", "else",
      "enum", "extends", "final", "finally", "float", "for", "if",
      "implements", "import", "instanceof", "int", "interface", "long",
      "native", "new", "package", "private", "protected", "public",
      "return", "short", "static", "strictfp", "super", "switch",
      "synchronized", "this", "throw", "throws", "transient", "try",
      "void", "volatile", "while", "true", "false", "null",
    ],
    types: ["byte", "short", "int", "long", "float", "double", "boolean", "char", "void"],
    topLevels: getTopLevels(),
    imports: getImports(),
    classes: getClasses() as unknown as Record<string, PluginEngineClass>,
    postfixTemplates: getJavaPostfixTemplates(),
  },
}

function getTopLevels(): PluginEngineTopLevel[] {
  return [
    { label: "String", insertText: "String", detail: "java.lang.String", kind: "class" },
    { label: "Integer", insertText: "Integer", detail: "java.lang.Integer", kind: "class" },
    { label: "Long", insertText: "Long", detail: "java.lang.Long", kind: "class" },
    { label: "Double", insertText: "Double", detail: "java.lang.Double", kind: "class" },
    { label: "Boolean", insertText: "Boolean", detail: "java.lang.Boolean", kind: "class" },
    { label: "Object", insertText: "Object", detail: "java.lang.Object", kind: "class" },
    { label: "System", insertText: "System", detail: "java.lang.System", kind: "class" },
    { label: "Math", insertText: "Math", detail: "java.lang.Math", kind: "class" },
    { label: "Thread", insertText: "Thread", detail: "java.lang.Thread", kind: "class" },
    { label: "Runtime", insertText: "Runtime", detail: "java.lang.Runtime", kind: "class" },
    { label: "Exception", insertText: "Exception", detail: "java.lang.Exception", kind: "class" },
    { label: "RuntimeException", insertText: "RuntimeException", detail: "java.lang.RuntimeException", kind: "class" },
    { label: "Throwable", insertText: "Throwable", detail: "java.lang.Throwable", kind: "class" },
    { label: "Error", insertText: "Error", detail: "java.lang.Error", kind: "class" },
    { label: "Override", insertText: "@Override", detail: "annotation", kind: "interface" },
    { label: "Deprecated", insertText: "@Deprecated", detail: "annotation", kind: "interface" },
    { label: "SuppressWarnings", insertText: "@SuppressWarnings", detail: "annotation", kind: "interface" },
    { label: "FunctionalInterface", insertText: "@FunctionalInterface", detail: "annotation", kind: "interface" },
    { label: "List", insertText: "List", detail: "java.util.List", kind: "interface" },
    { label: "ArrayList", insertText: "ArrayList", detail: "java.util.ArrayList", kind: "class" },
    { label: "LinkedList", insertText: "LinkedList", detail: "java.util.LinkedList", kind: "class" },
    { label: "Map", insertText: "Map", detail: "java.util.Map", kind: "interface" },
    { label: "HashMap", insertText: "HashMap", detail: "java.util.HashMap", kind: "class" },
    { label: "TreeMap", insertText: "TreeMap", detail: "java.util.TreeMap", kind: "class" },
    { label: "Set", insertText: "Set", detail: "java.util.Set", kind: "interface" },
    { label: "HashSet", insertText: "HashSet", detail: "java.util.HashSet", kind: "class" },
    { label: "Queue", insertText: "Queue", detail: "java.util.Queue", kind: "interface" },
    { label: "Stack", insertText: "Stack", detail: "java.util.Stack", kind: "class" },
    { label: "Optional", insertText: "Optional", detail: "java.util.Optional", kind: "class" },
    { label: "Stream", insertText: "Stream", detail: "java.util.stream.Stream", kind: "interface" },
    { label: "Collectors", insertText: "Collectors", detail: "java.util.stream.Collectors", kind: "class" },
    { label: "Comparator", insertText: "Comparator", detail: "java.util.Comparator", kind: "interface" },
    { label: "Collections", insertText: "Collections", detail: "java.util.Collections", kind: "class" },
    { label: "Arrays", insertText: "Arrays", detail: "java.util.Arrays", kind: "class" },
    { label: "Objects", insertText: "Objects", detail: "java.util.Objects", kind: "class" },
    { label: "LocalDate", insertText: "LocalDate", detail: "java.time.LocalDate", kind: "class" },
    { label: "LocalDateTime", insertText: "LocalDateTime", detail: "java.time.LocalDateTime", kind: "class" },
    { label: "Instant", insertText: "Instant", detail: "java.time.Instant", kind: "class" },
    { label: "Duration", insertText: "Duration", detail: "java.time.Duration", kind: "class" },
    { label: "DateTimeFormatter", insertText: "DateTimeFormatter", detail: "java.time.format.DateTimeFormatter", kind: "class" },
    { label: "BigDecimal", insertText: "BigDecimal", detail: "java.math.BigDecimal", kind: "class" },
    { label: "BigInteger", insertText: "BigInteger", detail: "java.math.BigInteger", kind: "class" },
    { label: "File", insertText: "File", detail: "java.io.File", kind: "class" },
    { label: "Path", insertText: "Path", detail: "java.nio.file.Path", kind: "interface" },
    { label: "Paths", insertText: "Paths", detail: "java.nio.file.Paths", kind: "class" },
    { label: "Files", insertText: "Files", detail: "java.nio.file.Files", kind: "class" },
    { label: "Pattern", insertText: "Pattern", detail: "java.util.regex.Pattern", kind: "class" },
    { label: "StringBuilder", insertText: "StringBuilder", detail: "java.lang.StringBuilder", kind: "class" },
    { label: "UUID", insertText: "UUID", detail: "java.util.UUID", kind: "class" },
    { label: "Random", insertText: "Random", detail: "java.util.Random", kind: "class" },
    { label: "Scanner", insertText: "Scanner", detail: "java.util.Scanner", kind: "class" },
    { label: "ExecutorService", insertText: "ExecutorService", detail: "java.util.concurrent.ExecutorService", kind: "interface" },
    { label: "Executors", insertText: "Executors", detail: "java.util.concurrent.Executors", kind: "class" },
    { label: "CompletableFuture", insertText: "CompletableFuture", detail: "java.util.concurrent.CompletableFuture", kind: "class" },
    { label: "InputStream", insertText: "InputStream", detail: "java.io.InputStream", kind: "class" },
    { label: "OutputStream", insertText: "OutputStream", detail: "java.io.OutputStream", kind: "class" },
    { label: "BufferedReader", insertText: "BufferedReader", detail: "java.io.BufferedReader", kind: "class" },
    { label: "Serializable", insertText: "Serializable", detail: "java.io.Serializable", kind: "interface" },
    { label: "Comparable", insertText: "Comparable", detail: "java.lang.Comparable", kind: "interface" },
    { label: "Iterable", insertText: "Iterable", detail: "java.lang.Iterable", kind: "interface" },
    { label: "Runnable", insertText: "Runnable", detail: "java.lang.Runnable", kind: "interface" },
    { label: "Callable", insertText: "Callable", detail: "java.util.concurrent.Callable", kind: "interface" },
    { label: "Supplier", insertText: "Supplier", detail: "java.util.function.Supplier", kind: "interface" },
    { label: "Consumer", insertText: "Consumer", detail: "java.util.function.Consumer", kind: "interface" },
    { label: "Function", insertText: "Function", detail: "java.util.function.Function", kind: "interface" },
    { label: "Predicate", insertText: "Predicate", detail: "java.util.function.Predicate", kind: "interface" },
  ]
}

function getImports(): PluginEngineTopLevel[] {
  return [
    { label: "java.util.List", insertText: "java.util.List", detail: "import", kind: "class" },
    { label: "java.util.ArrayList", insertText: "java.util.ArrayList", detail: "import", kind: "class" },
    { label: "java.util.Map", insertText: "java.util.Map", detail: "import", kind: "class" },
    { label: "java.util.HashMap", insertText: "java.util.HashMap", detail: "import", kind: "class" },
    { label: "java.util.Set", insertText: "java.util.Set", detail: "import", kind: "class" },
    { label: "java.util.Optional", insertText: "java.util.Optional", detail: "import", kind: "class" },
    { label: "java.util.stream.Stream", insertText: "java.util.stream.Stream", detail: "import", kind: "class" },
    { label: "java.util.stream.Collectors", insertText: "java.util.stream.Collectors", detail: "import", kind: "class" },
    { label: "java.time.LocalDate", insertText: "java.time.LocalDate", detail: "import", kind: "class" },
    { label: "java.time.LocalDateTime", insertText: "java.time.LocalDateTime", detail: "import", kind: "class" },
    { label: "java.util.Comparator", insertText: "java.util.Comparator", detail: "import", kind: "class" },
    { label: "java.util.Collections", insertText: "java.util.Collections", detail: "import", kind: "class" },
    { label: "java.util.Arrays", insertText: "java.util.Arrays", detail: "import", kind: "class" },
    { label: "java.util.Objects", insertText: "java.util.Objects", detail: "import", kind: "class" },
    { label: "java.math.BigDecimal", insertText: "java.math.BigDecimal", detail: "import", kind: "class" },
    { label: "java.io.File", insertText: "java.io.File", detail: "import", kind: "class" },
    { label: "java.nio.file.Path", insertText: "java.nio.file.Path", detail: "import", kind: "class" },
    { label: "java.nio.file.Paths", insertText: "java.nio.file.Paths", detail: "import", kind: "class" },
    { label: "java.nio.file.Files", insertText: "java.nio.file.Files", detail: "import", kind: "class" },
    { label: "java.util.regex.Pattern", insertText: "java.util.regex.Pattern", detail: "import", kind: "class" },
    { label: "java.util.concurrent.Executors", insertText: "java.util.concurrent.Executors", detail: "import", kind: "class" },
  ]
}

function getClasses(): Record<string, Record<string, unknown>> {
  return {
    String: {
      name: "String", detail: "java.lang.String",
      methods: [
        { name: "length", params: "()", returnType: "int", detail: "string length" },
        { name: "charAt", params: "(int)", returnType: "char", detail: "char at index" },
        { name: "substring", params: "(int,int)", returnType: "String", detail: "substring" },
        { name: "indexOf", params: "(String)", returnType: "int", detail: "find index" },
        { name: "contains", params: "(CharSequence)", returnType: "boolean", detail: "contains?" },
        { name: "startsWith", params: "(String)", returnType: "boolean", detail: "starts with?" },
        { name: "endsWith", params: "(String)", returnType: "boolean", detail: "ends with?" },
        { name: "isEmpty", params: "()", returnType: "boolean", detail: "is empty?" },
        { name: "isBlank", params: "()", returnType: "boolean", detail: "is blank? (JDK 11+)" },
        { name: "trim", params: "()", returnType: "String", detail: "trim whitespace" },
        { name: "strip", params: "()", returnType: "String", detail: "strip (JDK 11+)" },
        { name: "toUpperCase", params: "()", returnType: "String", detail: "upper case" },
        { name: "toLowerCase", params: "()", returnType: "String", detail: "lower case" },
        { name: "replace", params: "(CharSequence,CharSequence)", returnType: "String", detail: "replace" },
        { name: "replaceAll", params: "(String, String)", returnType: "String", detail: "replace regex" },
        { name: "split", params: "(String)", returnType: "String[]", detail: "split" },
        { name: "join", params: "(CharSequence, CharSequence...)", returnType: "static String", detail: "join (JDK 8+)" },
        { name: "format", params: "(String, Object...)", returnType: "static String", detail: "format" },
        { name: "valueOf", params: "(Object)", returnType: "static String", detail: "to string" },
        { name: "equals", params: "(Object)", returnType: "boolean", detail: "equals" },
        { name: "equalsIgnoreCase", params: "(String)", returnType: "boolean", detail: "equals ignore case" },
        { name: "compareTo", params: "(String)", returnType: "int", detail: "compare" },
        { name: "toCharArray", params: "()", returnType: "char[]", detail: "to char array" },
        { name: "getBytes", params: "()", returnType: "byte[]", detail: "to bytes" },
        { name: "matches", params: "(String)", returnType: "boolean", detail: "regex match" },
        { name: "concat", params: "(String)", returnType: "String", detail: "concat" },
        { name: "repeat", params: "(int)", returnType: "String", detail: "repeat (JDK 11+)" },
        { name: "lines", params: "()", returnType: "Stream<String>", detail: "lines stream (JDK 11+)" },
        { name: "chars", params: "()", returnType: "IntStream", detail: "char int stream" },
        { name: "stripLeading", params: "()", returnType: "String", detail: "strip leading (JDK 11+)" },
        { name: "stripTrailing", params: "()", returnType: "String", detail: "strip trailing (JDK 11+)" },
        { name: "indent", params: "(int)", returnType: "String", detail: "indent (JDK 12+)" },
        { name: "transform", params: "(Function)", returnType: "<R> R", detail: "transform (JDK 12+)" },
        { name: "formatted", params: "(Object...)", returnType: "String", detail: "formatted (JDK 15+)" },
        { name: "intern", params: "()", returnType: "String", detail: "intern" },
      ],
    },
    System: {
      name: "System", detail: "java.lang.System",
      staticFields: [
        { name: "out", type: "PrintStream", detail: "stdout" },
        { name: "err", type: "PrintStream", detail: "stderr" },
        { name: "in", type: "InputStream", detail: "stdin" },
      ],
      methods: [
        { name: "currentTimeMillis", params: "()", returnType: "static long", detail: "ms since epoch" },
        { name: "nanoTime", params: "()", returnType: "static long", detail: "nanos" },
        { name: "exit", params: "(int)", returnType: "static void", detail: "exit JVM" },
        { name: "gc", params: "()", returnType: "static void", detail: "run GC" },
        { name: "getenv", params: "(String)", returnType: "static String", detail: "env var" },
        { name: "getProperty", params: "(String)", returnType: "static String", detail: "sys property" },
        { name: "arraycopy", params: "(Object,int,Object,int,int)", returnType: "static void", detail: "copy array" },
        { name: "lineSeparator", params: "()", returnType: "static String", detail: "line separator (JDK 7+)" },
      ],
    },
    Math: {
      name: "Math", detail: "java.lang.Math",
      staticFields: [
        { name: "PI", type: "double", detail: "π" },
        { name: "E", type: "double", detail: "e" },
      ],
      methods: [
        { name: "abs", params: "(int/long/double)", returnType: "static", detail: "absolute" },
        { name: "max", params: "(int, int)", returnType: "static int", detail: "max" },
        { name: "min", params: "(int, int)", returnType: "static int", detail: "min" },
        { name: "pow", params: "(double, double)", returnType: "static double", detail: "a^b" },
        { name: "sqrt", params: "(double)", returnType: "static double", detail: "sqrt" },
        { name: "ceil", params: "(double)", returnType: "static double", detail: "ceil" },
        { name: "floor", params: "(double)", returnType: "static double", detail: "floor" },
        { name: "round", params: "(double)", returnType: "static long", detail: "round" },
        { name: "random", params: "()", returnType: "static double", detail: "random [0,1)" },
        { name: "log", params: "(double)", returnType: "static double", detail: "ln" },
        { name: "log10", params: "(double)", returnType: "static double", detail: "log10" },
        { name: "sin", params: "(double)", returnType: "static double", detail: "sine" },
        { name: "cos", params: "(double)", returnType: "static double", detail: "cosine" },
        { name: "tan", params: "(double)", returnType: "static double", detail: "tangent" },
        { name: "toDegrees", params: "(double)", returnType: "static double", detail: "radians to degrees" },
        { name: "toRadians", params: "(double)", returnType: "static double", detail: "degrees to radians" },
        { name: "hypot", params: "(double, double)", returnType: "static double", detail: "hypotenuse" },
        { name: "toIntExact", params: "(long)", returnType: "static int", detail: "exact int (JDK 8+)" },
      ],
    },
    PrintStream: {
      name: "PrintStream", detail: "java.io.PrintStream",
      methods: [
        { name: "println", params: "(Object)", returnType: "void", detail: "print line" },
        { name: "print", params: "(Object)", returnType: "void", detail: "print" },
        { name: "printf", params: "(String, Object...)", returnType: "PrintStream", detail: "format print" },
        { name: "flush", params: "()", returnType: "void", detail: "flush" },
        { name: "close", params: "()", returnType: "void", detail: "close" },
      ],
    },
    List: {
      name: "List<E>", detail: "java.util.List",
      staticFields: [
        { name: "of()", type: "static List<E>", detail: "create immutable (JDK 9+)" },
        { name: "copyOf()", type: "static List<E>", detail: "copy (JDK 10+)" },
      ],
      methods: [
        { name: "add", params: "(E)", returnType: "boolean", detail: "add" },
        { name: "addAll", params: "(Collection)", returnType: "boolean", detail: "add all" },
        { name: "get", params: "(int)", returnType: "E", detail: "get" },
        { name: "set", params: "(int, E)", returnType: "E", detail: "set" },
        { name: "remove", params: "(int/Object)", returnType: "E/boolean", detail: "remove" },
        { name: "removeIf", params: "(Predicate)", returnType: "boolean", detail: "remove if (JDK 8+)" },
        { name: "contains", params: "(Object)", returnType: "boolean", detail: "contains?" },
        { name: "indexOf", params: "(Object)", returnType: "int", detail: "index of" },
        { name: "size", params: "()", returnType: "int", detail: "size" },
        { name: "isEmpty", params: "()", returnType: "boolean", detail: "empty?" },
        { name: "clear", params: "()", returnType: "void", detail: "clear" },
        { name: "sort", params: "(Comparator)", returnType: "void", detail: "sort (JDK 8+)" },
        { name: "forEach", params: "(Consumer)", returnType: "void", detail: "for each (JDK 8+)" },
        { name: "stream", params: "()", returnType: "Stream<E>", detail: "stream (JDK 8+)" },
        { name: "parallelStream", params: "()", returnType: "Stream<E>", detail: "parallel stream (JDK 8+)" },
        { name: "toArray", params: "()", returnType: "Object[]", detail: "to array" },
        { name: "replaceAll", params: "(UnaryOperator)", returnType: "void", detail: "replace all (JDK 8+)" },
        { name: "iterator", params: "()", returnType: "Iterator<E>", detail: "iterator" },
        { name: "subList", params: "(int, int)", returnType: "List<E>", detail: "subList" },
      ],
    },
    Map: {
      name: "Map<K,V>", detail: "java.util.Map",
      staticFields: [
        { name: "of()", type: "static Map<K,V>", detail: "immutable (JDK 9+)" },
        { name: "entry()", type: "static Entry<K,V>", detail: "entry (JDK 9+)" },
        { name: "copyOf()", type: "static Map<K,V>", detail: "copy (JDK 10+)" },
      ],
      methods: [
        { name: "put", params: "(K, V)", returnType: "V", detail: "put" },
        { name: "putAll", params: "(Map)", returnType: "void", detail: "put all" },
        { name: "putIfAbsent", params: "(K, V)", returnType: "V", detail: "put if absent (JDK 8+)" },
        { name: "get", params: "(Object)", returnType: "V", detail: "get" },
        { name: "getOrDefault", params: "(Object, V)", returnType: "V", detail: "get or default (JDK 8+)" },
        { name: "remove", params: "(Object)", returnType: "V", detail: "remove" },
        { name: "containsKey", params: "(Object)", returnType: "boolean", detail: "contains key?" },
        { name: "containsValue", params: "(Object)", returnType: "boolean", detail: "contains value?" },
        { name: "size", params: "()", returnType: "int", detail: "size" },
        { name: "isEmpty", params: "()", returnType: "boolean", detail: "empty?" },
        { name: "clear", params: "()", returnType: "void", detail: "clear" },
        { name: "keySet", params: "()", returnType: "Set<K>", detail: "keys" },
        { name: "values", params: "()", returnType: "Collection<V>", detail: "values" },
        { name: "entrySet", params: "()", returnType: "Set<Entry>", detail: "entries" },
        { name: "forEach", params: "(BiConsumer)", returnType: "void", detail: "for each (JDK 8+)" },
        { name: "replaceAll", params: "(BiFunction)", returnType: "void", detail: "replace all (JDK 8+)" },
        { name: "computeIfAbsent", params: "(K, Function)", returnType: "V", detail: "compute if absent (JDK 8+)" },
        { name: "computeIfPresent", params: "(K, BiFunction)", returnType: "V", detail: "compute if present (JDK 8+)" },
        { name: "compute", params: "(K, BiFunction)", returnType: "V", detail: "compute (JDK 8+)" },
        { name: "merge", params: "(K, V, BiFunction)", returnType: "V", detail: "merge (JDK 8+)" },
      ],
    },
    Set: {
      name: "Set<E>", detail: "java.util.Set",
      staticFields: [
        { name: "of()", type: "static Set<E>", detail: "immutable (JDK 9+)" },
      ],
      methods: [
        { name: "add", params: "(E)", returnType: "boolean", detail: "add" },
        { name: "contains", params: "(Object)", returnType: "boolean", detail: "contains?" },
        { name: "remove", params: "(Object)", returnType: "boolean", detail: "remove" },
        { name: "size", params: "()", returnType: "int", detail: "size" },
        { name: "isEmpty", params: "()", returnType: "boolean", detail: "empty?" },
        { name: "clear", params: "()", returnType: "void", detail: "clear" },
        { name: "iterator", params: "()", returnType: "Iterator<E>", detail: "iterator" },
        { name: "stream", params: "()", returnType: "Stream<E>", detail: "stream (JDK 8+)" },
        { name: "toArray", params: "()", returnType: "Object[]", detail: "to array" },
        { name: "containsAll", params: "(Collection)", returnType: "boolean", detail: "contains all?" },
        { name: "addAll", params: "(Collection)", returnType: "boolean", detail: "add all" },
        { name: "removeAll", params: "(Collection)", returnType: "boolean", detail: "remove all" },
        { name: "retainAll", params: "(Collection)", returnType: "boolean", detail: "retain" },
      ],
    },
    Optional: {
      name: "Optional<T>", detail: "java.util.Optional (JDK 8+)",
      staticFields: [
        { name: "empty()", type: "static Optional<T>", detail: "empty optional" },
        { name: "of()", type: "static Optional<T>", detail: "optional of" },
        { name: "ofNullable()", type: "static Optional<T>", detail: "nullable optional" },
      ],
      methods: [
        { name: "get", params: "()", returnType: "T", detail: "get value" },
        { name: "orElse", params: "(T)", returnType: "T", detail: "or default" },
        { name: "orElseGet", params: "(Supplier)", returnType: "T", detail: "or supply" },
        { name: "orElseThrow", params: "()", returnType: "T", detail: "or throw" },
        { name: "isPresent", params: "()", returnType: "boolean", detail: "present?" },
        { name: "isEmpty", params: "()", returnType: "boolean", detail: "empty? (JDK 11+)" },
        { name: "ifPresent", params: "(Consumer)", returnType: "void", detail: "if present do" },
        { name: "map", params: "(Function)", returnType: "Optional<U>", detail: "map" },
        { name: "flatMap", params: "(Function)", returnType: "Optional<U>", detail: "flatMap" },
        { name: "filter", params: "(Predicate)", returnType: "Optional<T>", detail: "filter" },
        { name: "or", params: "(Supplier)", returnType: "Optional<T>", detail: "or (JDK 9+)" },
        { name: "ifPresentOrElse", params: "(Consumer, Runnable)", returnType: "void", detail: "ifPresentOrElse (JDK 9+)" },
        { name: "stream", params: "()", returnType: "Stream<T>", detail: "stream (JDK 9+)" },
      ],
    },
    Stream: {
      name: "Stream<T>", detail: "java.util.stream.Stream (JDK 8+)",
      methods: [
        { name: "filter", params: "(Predicate)", returnType: "Stream<T>", detail: "filter" },
        { name: "map", params: "(Function)", returnType: "Stream<R>", detail: "map" },
        { name: "flatMap", params: "(Function)", returnType: "Stream<R>", detail: "flatMap" },
        { name: "distinct", params: "()", returnType: "Stream<T>", detail: "distinct" },
        { name: "sorted", params: "()", returnType: "Stream<T>", detail: "sorted" },
        { name: "peek", params: "(Consumer)", returnType: "Stream<T>", detail: "peek" },
        { name: "limit", params: "(long)", returnType: "Stream<T>", detail: "limit" },
        { name: "skip", params: "(long)", returnType: "Stream<T>", detail: "skip" },
        { name: "forEach", params: "(Consumer)", returnType: "void", detail: "for each" },
        { name: "forEachOrdered", params: "(Consumer)", returnType: "void", detail: "ordered forEach" },
        { name: "toArray", params: "()", returnType: "Object[]", detail: "to array" },
        { name: "reduce", params: "(BinaryOperator)", returnType: "Optional<T>", detail: "reduce" },
        { name: "collect", params: "(Collector)", returnType: "R", detail: "collect" },
        { name: "count", params: "()", returnType: "long", detail: "count" },
        { name: "anyMatch", params: "(Predicate)", returnType: "boolean", detail: "any match?" },
        { name: "allMatch", params: "(Predicate)", returnType: "boolean", detail: "all match?" },
        { name: "noneMatch", params: "(Predicate)", returnType: "boolean", detail: "none match?" },
        { name: "findFirst", params: "()", returnType: "Optional<T>", detail: "find first" },
        { name: "findAny", params: "()", returnType: "Optional<T>", detail: "find any" },
        { name: "min", params: "(Comparator)", returnType: "Optional<T>", detail: "min" },
        { name: "max", params: "(Comparator)", returnType: "Optional<T>", detail: "max" },
        { name: "takeWhile", params: "(Predicate)", returnType: "Stream<T>", detail: "take while (JDK 9+)" },
        { name: "dropWhile", params: "(Predicate)", returnType: "Stream<T>", detail: "drop while (JDK 9+)" },
      ],
    },
    Collectors: {
      name: "Collectors", detail: "java.util.stream.Collectors (JDK 8+)",
      methods: [
        { name: "toList", params: "()", returnType: "static Collector", detail: "collect to list" },
        { name: "toSet", params: "()", returnType: "static Collector", detail: "collect to set" },
        { name: "toMap", params: "(Function,Function)", returnType: "static Collector", detail: "collect to map" },
        { name: "joining", params: "(CharSequence)", returnType: "static Collector", detail: "join strings" },
        { name: "counting", params: "()", returnType: "static Collector", detail: "count" },
        { name: "summingInt", params: "(ToIntFunction)", returnType: "static Collector", detail: "sum int" },
        { name: "averagingInt", params: "(ToIntFunction)", returnType: "static Collector", detail: "avg int" },
        { name: "groupingBy", params: "(Function)", returnType: "static Collector", detail: "group by" },
        { name: "partitioningBy", params: "(Predicate)", returnType: "static Collector", detail: "partition" },
        { name: "mapping", params: "(Function, Collector)", returnType: "static Collector", detail: "map downstream" },
        { name: "toUnmodifiableList", params: "()", returnType: "static Collector", detail: "unmodifiable (JDK 10+)" },
        { name: "toUnmodifiableSet", params: "()", returnType: "static Collector", detail: "unmodifiable (JDK 10+)" },
        { name: "filtering", params: "(Predicate, Collector)", returnType: "static Collector", detail: "filter (JDK 9+)" },
        { name: "flatMapping", params: "(Function, Collector)", returnType: "static Collector", detail: "flatMap (JDK 9+)" },
      ],
    },
    Collections: {
      name: "Collections", detail: "java.util.Collections",
      methods: [
        { name: "sort", params: "(List)", returnType: "static void", detail: "sort" },
        { name: "reverse", params: "(List)", returnType: "static void", detail: "reverse" },
        { name: "shuffle", params: "(List)", returnType: "static void", detail: "shuffle" },
        { name: "binarySearch", params: "(List, T)", returnType: "static int", detail: "binary search" },
        { name: "min", params: "(Collection)", returnType: "static T", detail: "min" },
        { name: "max", params: "(Collection)", returnType: "static T", detail: "max" },
        { name: "frequency", params: "(Collection, Object)", returnType: "static int", detail: "frequency" },
        { name: "unmodifiableList", params: "(List)", returnType: "static List", detail: "unmodifiable view" },
        { name: "unmodifiableSet", params: "(Set)", returnType: "static Set", detail: "unmodifiable view" },
        { name: "unmodifiableMap", params: "(Map)", returnType: "static Map", detail: "unmodifiable view" },
        { name: "synchronizedList", params: "(List)", returnType: "static List", detail: "sync view" },
        { name: "synchronizedMap", params: "(Map)", returnType: "static Map", detail: "sync view" },
        { name: "emptyList", params: "()", returnType: "static List", detail: "empty list" },
        { name: "emptySet", params: "()", returnType: "static Set", detail: "empty set" },
        { name: "emptyMap", params: "()", returnType: "static Map", detail: "empty map" },
        { name: "singletonList", params: "(T)", returnType: "static List", detail: "singleton list" },
      ],
    },
    Objects: {
      name: "Objects", detail: "java.util.Objects (JDK 7+)",
      methods: [
        { name: "requireNonNull", params: "(T)", returnType: "static T", detail: "require non-null" },
        { name: "isNull", params: "(Object)", returnType: "static boolean", detail: "is null?" },
        { name: "nonNull", params: "(Object)", returnType: "static boolean", detail: "non-null?" },
        { name: "equals", params: "(Object, Object)", returnType: "static boolean", detail: "null-safe equals" },
        { name: "hash", params: "(Object...)", returnType: "static int", detail: "hash" },
        { name: "toString", params: "(Object, String)", returnType: "static String", detail: "null-safe toString" },
        { name: "requireNonNullElse", params: "(T, T)", returnType: "static T", detail: "require non-null else (JDK 9+)" },
      ],
    },
    Files: {
      name: "Files", detail: "java.nio.file.Files (JDK 7+)",
      methods: [
        { name: "readString", params: "(Path)", returnType: "static String", detail: "read to string (JDK 11+)" },
        { name: "writeString", params: "(Path, CharSequence)", returnType: "static Path", detail: "write string (JDK 11+)" },
        { name: "readAllLines", params: "(Path)", returnType: "static List<String>", detail: "read lines" },
        { name: "readAllBytes", params: "(Path)", returnType: "static byte[]", detail: "read bytes" },
        { name: "write", params: "(Path, byte[])", returnType: "static Path", detail: "write bytes" },
        { name: "exists", params: "(Path)", returnType: "static boolean", detail: "exists?" },
        { name: "isDirectory", params: "(Path)", returnType: "static boolean", detail: "is dir?" },
        { name: "isRegularFile", params: "(Path)", returnType: "static boolean", detail: "is file?" },
        { name: "createDirectory", params: "(Path)", returnType: "static Path", detail: "create dir" },
        { name: "createDirectories", params: "(Path)", returnType: "static Path", detail: "create dirs" },
        { name: "createFile", params: "(Path)", returnType: "static Path", detail: "create file" },
        { name: "delete", params: "(Path)", returnType: "static void", detail: "delete" },
        { name: "deleteIfExists", params: "(Path)", returnType: "static boolean", detail: "delete if exists" },
        { name: "copy", params: "(Path, Path)", returnType: "static Path", detail: "copy" },
        { name: "move", params: "(Path, Path)", returnType: "static Path", detail: "move" },
        { name: "walk", params: "(Path)", returnType: "static Stream<Path>", detail: "walk tree (JDK 8+)" },
        { name: "list", params: "(Path)", returnType: "static Stream<Path>", detail: "list dir (JDK 8+)" },
        { name: "find", params: "(Path, int, BiPredicate)", returnType: "static Stream<Path>", detail: "find (JDK 8+)" },
        { name: "lines", params: "(Path)", returnType: "static Stream<String>", detail: "stream lines (JDK 8+)" },
        { name: "size", params: "(Path)", returnType: "static long", detail: "file size" },
        { name: "newBufferedReader", params: "(Path)", returnType: "static BufferedReader", detail: "buffered reader" },
        { name: "newBufferedWriter", params: "(Path)", returnType: "static BufferedWriter", detail: "buffered writer" },
        { name: "walkFileTree", params: "(Path, FileVisitor)", returnType: "static Path", detail: "walk tree" },
        { name: "mismatch", params: "(Path, Path)", returnType: "static long", detail: "mismatch (JDK 12+)" },
      ],
    },
    StringBuilder: {
      name: "StringBuilder", detail: "java.lang.StringBuilder",
      methods: [
        { name: "append", params: "(Object)", returnType: "StringBuilder", detail: "append" },
        { name: "insert", params: "(int, Object)", returnType: "StringBuilder", detail: "insert" },
        { name: "delete", params: "(int, int)", returnType: "StringBuilder", detail: "delete" },
        { name: "deleteCharAt", params: "(int)", returnType: "StringBuilder", detail: "delete char" },
        { name: "replace", params: "(int, int, String)", returnType: "StringBuilder", detail: "replace" },
        { name: "reverse", params: "()", returnType: "StringBuilder", detail: "reverse" },
        { name: "charAt", params: "(int)", returnType: "char", detail: "char at" },
        { name: "substring", params: "(int, int)", returnType: "String", detail: "substring" },
        { name: "length", params: "()", returnType: "int", detail: "length" },
        { name: "setLength", params: "(int)", returnType: "void", detail: "set length" },
        { name: "toString", params: "()", returnType: "String", detail: "to string" },
        { name: "indexOf", params: "(String)", returnType: "int", detail: "index of" },
      ],
    },
    LocalDate: {
      name: "LocalDate", detail: "java.time.LocalDate (JDK 8+)",
      staticFields: [
        { name: "MIN", type: "LocalDate", detail: "minimum date" },
        { name: "MAX", type: "LocalDate", detail: "maximum date" },
      ],
      methods: [
        { name: "now", params: "()", returnType: "static LocalDate", detail: "today" },
        { name: "of", params: "(int, int, int)", returnType: "static LocalDate", detail: "create" },
        { name: "parse", params: "(CharSequence)", returnType: "static LocalDate", detail: "parse ISO" },
        { name: "getYear", params: "()", returnType: "int", detail: "year" },
        { name: "getMonth", params: "()", returnType: "Month", detail: "month" },
        { name: "getDayOfMonth", params: "()", returnType: "int", detail: "day" },
        { name: "getDayOfWeek", params: "()", returnType: "DayOfWeek", detail: "day of week" },
        { name: "plusDays", params: "(long)", returnType: "LocalDate", detail: "add days" },
        { name: "plusMonths", params: "(long)", returnType: "LocalDate", detail: "add months" },
        { name: "plusYears", params: "(long)", returnType: "LocalDate", detail: "add years" },
        { name: "minusDays", params: "(long)", returnType: "LocalDate", detail: "subtract days" },
        { name: "isAfter", params: "(LocalDate)", returnType: "boolean", detail: "after?" },
        { name: "isBefore", params: "(LocalDate)", returnType: "boolean", detail: "before?" },
        { name: "isEqual", params: "(LocalDate)", returnType: "boolean", detail: "equal?" },
        { name: "isLeapYear", params: "()", returnType: "boolean", detail: "leap year?" },
        { name: "format", params: "(DateTimeFormatter)", returnType: "String", detail: "format" },
        { name: "atStartOfDay", params: "()", returnType: "LocalDateTime", detail: "start of day" },
      ],
    },
    HttpClient: {
      name: "HttpClient", detail: "java.net.http.HttpClient (JDK 11+)",
      methods: [
        { name: "send", params: "(HttpRequest, BodyHandler)", returnType: "HttpResponse<T>", detail: "send" },
        { name: "sendAsync", params: "(HttpRequest, BodyHandler)", returnType: "CompletableFuture<HttpResponse<T>>", detail: "send async" },
      ],
      staticFields: [
        { name: "newHttpClient()", type: "static HttpClient", detail: "create client" },
        { name: "newBuilder()", type: "static Builder", detail: "create builder" },
      ],
    },
  }
}

function getJavaPostfixTemplates(): PluginPostfixTemplate[] {
  return [
    { key: "sout", label: "System.out.println", description: "Prints to stdout", snippet: "System.out.println(${1:expr})", applicable: ["String", "int", "Object"] },
    { key: "serr", label: "System.err.println", description: "Prints to stderr", snippet: "System.err.println(${1:expr})" },
    { key: "psvm", label: "public static void main", description: "Main method", snippet: "public static void main(String[] args) {\n    ${1}\n}" },
    { key: "for", label: "for-each loop", description: "For-each loop", snippet: "for ($1 item : ${2:collection}) {\n    ${3}\n}" },
    { key: "fori", label: "for index loop", description: "Indexed for loop", snippet: "for (int i = 0; i < ${1:n}; i++) {\n    ${2}\n}" },
    { key: "if", label: "if statement", description: "If statement", snippet: "if (${1:condition}) {\n    ${2}\n}" },
    { key: "ifn", label: "if != null", description: "If not null", snippet: "if (${1:expr} != null) {\n    ${2}\n}" },
    { key: "null", label: "if == null", description: "If null check", snippet: "if (${1:expr} == null) {\n    ${2}\n}" },
    { key: "while", label: "while loop", description: "While loop", snippet: "while (${1:condition}) {\n    ${2}\n}" },
    { key: "try", label: "try-catch", description: "Try-catch block", snippet: "try {\n    ${1}\n} catch (${2:Exception} e) {\n    ${3}\n}" },
    { key: "var", label: "declare variable", description: "Variable declaration", snippet: "${1:Type} ${2:name} = ${3:expr}" },
    { key: "cast", label: "cast", description: "Type cast", snippet: "((${1:Type}) ${2:expr})" },
    { key: "ret", label: "return value", description: "Return statement", snippet: "return ${1:expr}" },
    { key: "new", label: "new instance", description: "Create new instance", snippet: "new ${1:Type}(${2})" },
    { key: "inst", label: "instanceof check", description: "instanceof + cast", snippet: "if (${1:expr} instanceof ${2:Type}) {\n    ${2:Type} ${3:var} = (${2:Type}) ${1:expr};\n    ${4}\n}" },
    { key: "opt", label: "Optional.ofNullable", description: "Optional wrapper", snippet: "Optional.ofNullable(${1:expr})" },
    { key: "lst", label: "new ArrayList", description: "ArrayList creation", snippet: "new ArrayList<>()" },
    { key: "hmap", label: "new HashMap", description: "HashMap creation", snippet: "new HashMap<>()" },
    { key: "hset", label: "new HashSet", description: "HashSet creation", snippet: "new HashSet<>()" },
    { key: "sb", label: "new StringBuilder", description: "StringBuilder", snippet: "new StringBuilder()" },
    { key: "swap", label: "switch statement", description: "Switch expression", snippet: "switch (${1:expr}) {\n    case ${2}:\n        ${3}\n        break;\n    default:\n        ${4}\n}" },
    { key: "syn", label: "synchronized block", description: "Synchronized block", snippet: "synchronized (${1:lock}) {\n    ${2}\n}" },
    { key: "lam", label: "lambda", description: "Lambda expression", snippet: "(${1}) -> ${2}" },
  ]
}