import type { PluginManifest, PluginEngineTopLevel, PluginPostfixTemplate, PluginEngineClass } from "../types"

export const pythonPluginManifest: PluginManifest = {
  id: "codek-python-intellisense",
  name: "codek-python",
  displayName: "Python IntelliSense",
  version: "2.0.0",
  publisher: "Codek Team",
  description: "Python code completion with full standard library support.",
  icon: "PY",
  license: "MIT",
  keywords: ["python", "intellisense", "completion"],
  categories: ["languages"],
  language: "python",
  engines: { codek: "*" },
  activationEvents: ["onLanguage:python"],
  extensionDependencies: [],
  contributes: { languages: [{ id: "python", aliases: ["Python", "py"], extensions: [".py", ".pyi", ".pyx", ".pyw"] }], snippets: {} },
  snippets: [],
  preview: false,
  size: 38 * 1024,
  engineConfig: {
    keywords: getKeywords(),
    types: ["int", "float", "str", "bytes", "bool", "list", "tuple", "dict", "set", "frozenset", "None", "True", "False"],
    topLevels: getTopLevels(),
    imports: getImports(),
    classes: getClasses() as unknown as Record<string, PluginEngineClass>,
    postfixTemplates: getPythonPostfixTemplates(),
  },
}

function getKeywords(): string[] {
  return [
    "False", "None", "True", "and", "as", "assert", "async", "await",
    "break", "class", "continue", "def", "del", "elif", "else", "except",
    "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "nonlocal", "not", "or", "pass", "raise", "return",
    "try", "while", "with", "yield", "self", "cls",
  ]
}

function getTopLevels(): PluginEngineTopLevel[] {
  return [
    { label: "print", insertText: "print(${1:value})", detail: "print to stdout", kind: "method" },
    { label: "len", insertText: "len(${1:obj})", detail: "get length", kind: "method" },
    { label: "range", insertText: "range(${1:stop})", detail: "range iterator", kind: "class" },
    { label: "enumerate", insertText: "enumerate(${1:iterable})", detail: "enumerate", kind: "method" },
    { label: "zip", insertText: "zip(${1:iterables})", detail: "zip iterables", kind: "method" },
    { label: "map", insertText: "map(${1:func}, ${2:iterable})", detail: "map function", kind: "method" },
    { label: "filter", insertText: "filter(${1:func}, ${2:iterable})", detail: "filter", kind: "method" },
    { label: "sorted", insertText: "sorted(${1:iterable})", detail: "sorted list", kind: "method" },
    { label: "reversed", insertText: "reversed(${1:seq})", detail: "reversed iterator", kind: "method" },
    { label: "any", insertText: "any(${1:iterable})", detail: "any True", kind: "method" },
    { label: "all", insertText: "all(${1:iterable})", detail: "all True", kind: "method" },
    { label: "sum", insertText: "sum(${1:iterable})", detail: "sum", kind: "method" },
    { label: "min", insertText: "min(${1:iterable})", detail: "minimum", kind: "method" },
    { label: "max", insertText: "max(${1:iterable})", detail: "maximum", kind: "method" },
    { label: "abs", insertText: "abs(${1:x})", detail: "absolute value", kind: "method" },
    { label: "round", insertText: "round(${1:number})", detail: "round", kind: "method" },
    { label: "pow", insertText: "pow(${1:base}, ${2:exp})", detail: "power", kind: "method" },
    { label: "divmod", insertText: "divmod(${1:a}, ${2:b})", detail: "divmod", kind: "method" },
    { label: "isinstance", insertText: "isinstance(${1:obj}, ${2:class})", detail: "type check", kind: "method" },
    { label: "issubclass", insertText: "issubclass(${1:cls}, ${2:class})", detail: "subclass check", kind: "method" },
    { label: "hasattr", insertText: "hasattr(${1:obj}, ${2:name})", detail: "has attribute", kind: "method" },
    { label: "getattr", insertText: "getattr(${1:obj}, ${2:name})", detail: "get attribute", kind: "method" },
    { label: "setattr", insertText: "setattr(${1:obj}, ${2:name}, ${3:value})", detail: "set attribute", kind: "method" },
    { label: "delattr", insertText: "delattr(${1:obj}, ${2:name})", detail: "delete attribute", kind: "method" },
    { label: "type", insertText: "type(${1:obj})", detail: "get type", kind: "class" },
    { label: "id", insertText: "id(${1:obj})", detail: "object id", kind: "method" },
    { label: "hash", insertText: "hash(${1:obj})", detail: "hash value", kind: "method" },
    { label: "repr", insertText: "repr(${1:obj})", detail: "representation", kind: "method" },
    { label: "str", insertText: "str(${1:obj})", detail: "to string", kind: "class" },
    { label: "int", insertText: "int(${1:x})", detail: "to int", kind: "class" },
    { label: "float", insertText: "float(${1:x})", detail: "to float", kind: "class" },
    { label: "bool", insertText: "bool(${1:x})", detail: "to bool", kind: "class" },
    { label: "bytes", insertText: "bytes(${1:source})", detail: "bytes", kind: "class" },
    { label: "bytearray", insertText: "bytearray(${1:source})", detail: "bytearray", kind: "class" },
    { label: "list", insertText: "list(${1:iterable})", detail: "to list", kind: "class" },
    { label: "tuple", insertText: "tuple(${1:iterable})", detail: "to tuple", kind: "class" },
    { label: "dict", insertText: "dict(${1:kwargs})", detail: "to dict", kind: "class" },
    { label: "set", insertText: "set(${1:iterable})", detail: "to set", kind: "class" },
    { label: "frozenset", insertText: "frozenset(${1:iterable})", detail: "frozenset", kind: "class" },
    { label: "slice", insertText: "slice(${1:start}, ${2:stop})", detail: "slice", kind: "class" },
    { label: "open", insertText: "open(${1:file}, '${2:r}')", detail: "open file", kind: "method" },
    { label: "input", insertText: "input(${1:prompt})", detail: "read stdin", kind: "method" },
    { label: "iter", insertText: "iter(${1:obj})", detail: "get iterator", kind: "method" },
    { label: "next", insertText: "next(${1:iterator})", detail: "next item", kind: "method" },
    { label: "ord", insertText: "ord(${1:char})", detail: "char to int", kind: "method" },
    { label: "chr", insertText: "chr(${1:code})", detail: "int to char", kind: "method" },
    { label: "bin", insertText: "bin(${1:x})", detail: "to binary", kind: "method" },
    { label: "hex", insertText: "hex(${1:x})", detail: "to hex", kind: "method" },
    { label: "oct", insertText: "oct(${1:x})", detail: "to octal", kind: "method" },
    { label: "format", insertText: "format(${1:value}, ${2:spec})", detail: "format", kind: "method" },
    { label: "dir", insertText: "dir(${1:obj})", detail: "list attributes", kind: "method" },
    { label: "vars", insertText: "vars(${1:obj})", detail: "dict of attributes", kind: "method" },
    { label: "callable", insertText: "callable(${1:obj})", detail: "is callable", kind: "method" },
    { label: "compile", insertText: "compile(${1:source}, ${2:filename}, ${3:mode})", detail: "compile code", kind: "method" },
    { label: "eval", insertText: "eval(${1:expression})", detail: "eval", kind: "method" },
    { label: "exec", insertText: "exec(${1:code})", detail: "exec", kind: "method" },
    { label: "staticmethod", insertText: "@staticmethod", detail: "staticmethod decorator", kind: "snippet" },
    { label: "classmethod", insertText: "@classmethod", detail: "classmethod decorator", kind: "snippet" },
    { label: "property", insertText: "@property", detail: "property decorator", kind: "snippet" },
    { label: "abstractmethod", insertText: "@abstractmethod", detail: "abstractmethod decorator", kind: "snippet" },
    { label: "dataclass", insertText: "@dataclass", detail: "dataclass decorator", kind: "snippet" },
    { label: "Exception", insertText: "Exception", detail: "base exception", kind: "class" },
    { label: "ValueError", insertText: "ValueError", detail: "value error", kind: "class" },
    { label: "TypeError", insertText: "TypeError", detail: "type error", kind: "class" },
    { label: "KeyError", insertText: "KeyError", detail: "key error", kind: "class" },
    { label: "IndexError", insertText: "IndexError", detail: "index error", kind: "class" },
    { label: "FileNotFoundError", insertText: "FileNotFoundError", detail: "file not found", kind: "class" },
    { label: "IOError", insertText: "IOError", detail: "IO error", kind: "class" },
    { label: "OSError", insertText: "OSError", detail: "OS error", kind: "class" },
    { label: "StopIteration", insertText: "StopIteration", detail: "stop iteration", kind: "class" },
    { label: "NotImplementedError", insertText: "NotImplementedError", detail: "not implemented", kind: "class" },
  ]
}

function getImports(): PluginEngineTopLevel[] {
  return [
    { label: "os", insertText: "import os", detail: "operating system interface", kind: "module" },
    { label: "sys", insertText: "import sys", detail: "system-specific parameters", kind: "module" },
    { label: "json", insertText: "import json", detail: "JSON encoder/decoder", kind: "module" },
    { label: "re", insertText: "import re", detail: "regular expressions", kind: "module" },
    { label: "math", insertText: "import math", detail: "mathematical functions", kind: "module" },
    { label: "random", insertText: "import random", detail: "random number generators", kind: "module" },
    { label: "datetime", insertText: "import datetime", detail: "date and time", kind: "module" },
    { label: "collections", insertText: "import collections", detail: "container datatypes", kind: "module" },
    { label: "itertools", insertText: "import itertools", detail: "iterator tools", kind: "module" },
    { label: "functools", insertText: "import functools", detail: "higher-order functions", kind: "module" },
    { label: "pathlib", insertText: "import pathlib", detail: "object-oriented paths", kind: "module" },
    { label: "typing", insertText: "import typing", detail: "type hints", kind: "module" },
    { label: "logging", insertText: "import logging", detail: "logging facility", kind: "module" },
    { label: "uuid", insertText: "import uuid", detail: "UUID objects", kind: "module" },
    { label: "hashlib", insertText: "import hashlib", detail: "secure hashes", kind: "module" },
    { label: "base64", insertText: "import base64", detail: "base64 encoding", kind: "module" },
    { label: "subprocess", insertText: "import subprocess", detail: "subprocess management", kind: "module" },
    { label: "argparse", insertText: "import argparse", detail: "argument parsing", kind: "module" },
    { label: "csv", insertText: "import csv", detail: "CSV file reading/writing", kind: "module" },
    { label: "io", insertText: "import io", detail: "IO streams", kind: "module" },
    { label: "shutil", insertText: "import shutil", detail: "high-level file operations", kind: "module" },
    { label: "tempfile", insertText: "import tempfile", detail: "temporary files", kind: "module" },
    { label: "threading", insertText: "import threading", detail: "thread-based parallelism", kind: "module" },
    { label: "asyncio", insertText: "import asyncio", detail: "async I/O", kind: "module" },
    { label: "dataclasses", insertText: "import dataclasses", detail: "dataclass decorator", kind: "module" },
    { label: "enum", insertText: "import enum", detail: "enumerations", kind: "module" },
    { label: "abc", insertText: "import abc", detail: "abstract base classes", kind: "module" },
    { label: "copy", insertText: "import copy", detail: "shallow/deep copy", kind: "module" },
    { label: "time", insertText: "import time", detail: "time access", kind: "module" },
    { label: "unittest", insertText: "import unittest", detail: "unit testing", kind: "module" },
  ]
}

function getClasses(): Record<string, Record<string, unknown>> {
  return {
    str: {
      name: "str", detail: "builtins.str",
      methods: [
        { name: "capitalize", params: "()", returnType: "str", detail: "capitalize first char" },
        { name: "casefold", params: "()", returnType: "str", detail: "casefold for caseless matching" },
        { name: "center", params: "(width)", returnType: "str", detail: "center in field" },
        { name: "count", params: "(sub)", returnType: "int", detail: "count occurrences" },
        { name: "encode", params: "()", returnType: "bytes", detail: "encode to bytes" },
        { name: "endswith", params: "(suffix)", returnType: "bool", detail: "ends with suffix" },
        { name: "find", params: "(sub)", returnType: "int", detail: "find substring, -1 if not found" },
        { name: "format", params: "(*args)", returnType: "str", detail: "format string" },
        { name: "format_map", params: "(mapping)", returnType: "str", detail: "format with mapping" },
        { name: "index", params: "(sub)", returnType: "int", detail: "index of substring" },
        { name: "isalnum", params: "()", returnType: "bool", detail: "is alphanumeric" },
        { name: "isalpha", params: "()", returnType: "bool", detail: "is alphabetic" },
        { name: "isascii", params: "()", returnType: "bool", detail: "is ASCII" },
        { name: "isdecimal", params: "()", returnType: "bool", detail: "is decimal" },
        { name: "isdigit", params: "()", returnType: "bool", detail: "is digit" },
        { name: "isidentifier", params: "()", returnType: "bool", detail: "is valid identifier" },
        { name: "islower", params: "()", returnType: "bool", detail: "is lowercase" },
        { name: "isnumeric", params: "()", returnType: "bool", detail: "is numeric" },
        { name: "isspace", params: "()", returnType: "bool", detail: "is whitespace" },
        { name: "istitle", params: "()", returnType: "bool", detail: "is titlecase" },
        { name: "isupper", params: "()", returnType: "bool", detail: "is uppercase" },
        { name: "join", params: "(iterable)", returnType: "str", detail: "join strings" },
        { name: "ljust", params: "(width)", returnType: "str", detail: "left justify" },
        { name: "lower", params: "()", returnType: "str", detail: "to lowercase" },
        { name: "lstrip", params: "()", returnType: "str", detail: "strip left" },
        { name: "partition", params: "(sep)", returnType: "tuple", detail: "partition at sep" },
        { name: "removeprefix", params: "(prefix)", returnType: "str", detail: "remove prefix" },
        { name: "removesuffix", params: "(suffix)", returnType: "str", detail: "remove suffix" },
        { name: "replace", params: "(old, new)", returnType: "str", detail: "replace all" },
        { name: "rfind", params: "(sub)", returnType: "int", detail: "find from right" },
        { name: "rindex", params: "(sub)", returnType: "int", detail: "index from right" },
        { name: "rjust", params: "(width)", returnType: "str", detail: "right justify" },
        { name: "rpartition", params: "(sep)", returnType: "tuple", detail: "partition from right" },
        { name: "rsplit", params: "(sep)", returnType: "list", detail: "split from right" },
        { name: "rstrip", params: "()", returnType: "str", detail: "strip right" },
        { name: "split", params: "(sep)", returnType: "list", detail: "split string" },
        { name: "splitlines", params: "()", returnType: "list", detail: "split at line boundaries" },
        { name: "startswith", params: "(prefix)", returnType: "bool", detail: "starts with prefix" },
        { name: "strip", params: "()", returnType: "str", detail: "strip whitespace" },
        { name: "swapcase", params: "()", returnType: "str", detail: "swap case" },
        { name: "title", params: "()", returnType: "str", detail: "to titlecase" },
        { name: "upper", params: "()", returnType: "str", detail: "to uppercase" },
        { name: "zfill", params: "(width)", returnType: "str", detail: "zero fill" },
      ],
    },
    list: {
      name: "list", detail: "builtins.list",
      methods: [
        { name: "append", params: "(item)", returnType: "None", detail: "append item" },
        { name: "extend", params: "(iterable)", returnType: "None", detail: "extend with iterable" },
        { name: "insert", params: "(index, item)", returnType: "None", detail: "insert at index" },
        { name: "remove", params: "(item)", returnType: "None", detail: "remove first occurrence" },
        { name: "pop", params: "(index=-1)", returnType: "item", detail: "pop item at index" },
        { name: "clear", params: "()", returnType: "None", detail: "clear list" },
        { name: "index", params: "(item)", returnType: "int", detail: "index of item" },
        { name: "count", params: "(item)", returnType: "int", detail: "count occurrences" },
        { name: "sort", params: "(key=None, reverse=False)", returnType: "None", detail: "sort in place" },
        { name: "reverse", params: "()", returnType: "None", detail: "reverse in place" },
        { name: "copy", params: "()", returnType: "list", detail: "shallow copy" },
      ],
    },
    dict: {
      name: "dict", detail: "builtins.dict",
      methods: [
        { name: "clear", params: "()", returnType: "None", detail: "clear dict" },
        { name: "copy", params: "()", returnType: "dict", detail: "shallow copy" },
        { name: "get", params: "(key, default=None)", returnType: "value", detail: "get with default" },
        { name: "items", params: "()", returnType: "dict_items", detail: "key-value pairs" },
        { name: "keys", params: "()", returnType: "dict_keys", detail: "keys view" },
        { name: "values", params: "()", returnType: "dict_values", detail: "values view" },
        { name: "pop", params: "(key, default=None)", returnType: "value", detail: "pop key" },
        { name: "popitem", params: "()", returnType: "tuple", detail: "pop last item" },
        { name: "update", params: "(other)", returnType: "None", detail: "update from other" },
        { name: "setdefault", params: "(key, default=None)", returnType: "value", detail: "set default" },
        { name: "fromkeys", params: "(iterable, value=None)", returnType: "static dict", detail: "create from keys" },
      ],
    },
    set: {
      name: "set", detail: "builtins.set",
      methods: [
        { name: "add", params: "(item)", returnType: "None", detail: "add item" },
        { name: "clear", params: "()", returnType: "None", detail: "clear set" },
        { name: "copy", params: "()", returnType: "set", detail: "shallow copy" },
        { name: "discard", params: "(item)", returnType: "None", detail: "remove if exists" },
        { name: "pop", params: "()", returnType: "item", detail: "pop arbitrary item" },
        { name: "remove", params: "(item)", returnType: "None", detail: "remove item" },
        { name: "union", params: "(*others)", returnType: "set", detail: "union of sets" },
        { name: "intersection", params: "(*others)", returnType: "set", detail: "intersection" },
        { name: "difference", params: "(*others)", returnType: "set", detail: "difference" },
        { name: "symmetric_difference", params: "(other)", returnType: "set", detail: "symmetric diff" },
        { name: "isdisjoint", params: "(other)", returnType: "bool", detail: "no common items" },
        { name: "issubset", params: "(other)", returnType: "bool", detail: "is subset" },
        { name: "issuperset", params: "(other)", returnType: "bool", detail: "is superset" },
        { name: "update", params: "(*others)", returnType: "None", detail: "update with union" },
        { name: "intersection_update", params: "(*others)", returnType: "None", detail: "keep intersection" },
        { name: "difference_update", params: "(*others)", returnType: "None", detail: "remove others" },
      ],
    },
    tuple: {
      name: "tuple", detail: "builtins.tuple",
      methods: [
        { name: "count", params: "(item)", returnType: "int", detail: "count occurrences" },
        { name: "index", params: "(item)", returnType: "int", detail: "index of item" },
      ],
    },
    bytes: {
      name: "bytes", detail: "builtins.bytes",
      methods: [
        { name: "decode", params: "(encoding='utf-8')", returnType: "str", detail: "decode to str" },
        { name: "hex", params: "()", returnType: "str", detail: "hex representation" },
        { name: "fromhex", params: "(string)", returnType: "static bytes", detail: "from hex string" },
      ],
    },
    int: {
      name: "int", detail: "builtins.int",
      methods: [
        { name: "bit_length", params: "()", returnType: "int", detail: "bits needed" },
        { name: "to_bytes", params: "(length, byteorder)", returnType: "bytes", detail: "to bytes" },
        { name: "from_bytes", params: "(bytes, byteorder)", returnType: "static int", detail: "from bytes" },
      ],
    },
    float: {
      name: "float", detail: "builtins.float",
      methods: [
        { name: "as_integer_ratio", params: "()", returnType: "tuple", detail: "as fraction" },
        { name: "is_integer", params: "()", returnType: "bool", detail: "is integer" },
        { name: "hex", params: "()", returnType: "str", detail: "hex representation" },
      ],
    },
  }
}

function getPythonPostfixTemplates(): PluginPostfixTemplate[] {
  return [
    { key: "print", label: "print()", description: "Print expression", snippet: "print(${1:expr})" },
    { key: "for", label: "for loop", description: "For loop", snippet: "for ${1:item} in ${2:iterable}:\n    ${3}" },
    { key: "if", label: "if statement", description: "If block", snippet: "if ${1:condition}:\n    ${2}" },
    { key: "ifn", label: "if is not None", description: "If not None", snippet: "if ${1:expr} is not None:\n    ${2}" },
    { key: "def", label: "def function", description: "Function definition", snippet: "def ${1:name}(${2:params}):\n    \"\"\"${3:docstring}\"\"\"\n    ${4}" },
    { key: "cls", label: "class", description: "Class definition", snippet: "class ${1:Name}:\n    def __init__(self):\n        ${2}" },
    { key: "try", label: "try-except", description: "Try-except", snippet: "try:\n    ${1}\nexcept ${2:Exception} as e:\n    ${3}" },
    { key: "list", label: "list comprehension", description: "List comprehension", snippet: "[${1:expr} for ${2:item} in ${3:iterable}]" },
    { key: "dict", label: "dict comprehension", description: "Dict comprehension", snippet: "{${1:key}: ${2:value} for ${3:item} in ${4:iterable}}" },
    { key: "with", label: "with statement", description: "Context manager", snippet: "with ${1:expr} as ${2:var}:\n    ${3}" },
    { key: "main", label: "__main__ guard", description: "Main guard", snippet: "if __name__ == \"__main__\":\n    ${1}" },
    { key: "ret", label: "return", description: "Return statement", snippet: "return ${1:expr}" },
    { key: "lam", label: "lambda", description: "Lambda expression", snippet: "lambda ${1:x}: ${2:expr}" },
    { key: "dec", label: "decorator", description: "Decorator", snippet: "@${1:decorator}\ndef ${2:name}(${3}):\n    ${4}" },
    { key: "prop", label: "property", description: "Property decorator", snippet: "@property\ndef ${1:name}(self):\n    return ${2}" },
    { key: "enum", label: "enumerate", description: "Enumerate loop", snippet: "for ${1:i}, ${2:item} in enumerate(${3:iterable}):\n    ${4}" },
    { key: "zip", label: "zip loop", description: "Zip loop", snippet: "for ${1:a}, ${2:b} in zip(${3:iter1}, ${4:iter2}):\n    ${5}" },
    { key: "join", label: "str.join", description: "Join strings", snippet: "\"${1:sep}\".join(${2:iterable})" },
    { key: "fmt", label: "f-string", description: "Format string", snippet: "f\"${1:text}\"" },
  ]
}