import type { PluginManifest, PluginEngineTopLevel, PluginEngineClass } from "../types"

export const rustPluginManifest: PluginManifest = {
  id: "codek-rust-intellisense",
  name: "codek-rust",
  displayName: "Rust IntelliSense",
  version: "1.0.0",
  publisher: "Codek Team",
  description: "Rust language code completion with standard library support.",
  icon: "RS",
  license: "MIT",
  keywords: ["rust", "intellisense", "completion", "cargo", "standard-library"],
  categories: ["languages"],
  language: "rust",
  engines: { codek: "*" },
  activationEvents: ["onLanguage:rust"],
  extensionDependencies: [],
  contributes: { languages: [{ id: "rust", aliases: ["Rust", "rust"], extensions: [".rs"] }], snippets: {} },
  snippets: [],
  preview: false,
  size: 20 * 1024,
  engineConfig: {
    keywords: getKeywords(),
    types: getTypes(),
    topLevels: getTopLevels(),
    imports: getImports(),
    classes: getClasses() as unknown as Record<string, PluginEngineClass>,
  },
}

function getKeywords(): string[] {
  return [
    "as", "async", "await", "break", "const", "continue", "crate", "dyn",
    "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in",
    "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true", "type",
    "union", "unsafe", "use", "where", "while", "yield",
  ]
}

function getTypes(): string[] {
  return [
    "i8", "i16", "i32", "i64", "i128", "isize",
    "u8", "u16", "u32", "u64", "u128", "usize",
    "f32", "f64", "bool", "char", "str", "String",
    "Vec", "Option", "Result", "Box", "Rc", "Arc",
    "Cell", "RefCell", "Mutex", "RwLock",
    "HashMap", "BTreeMap", "HashSet", "BTreeSet",
    "BinaryHeap", "VecDeque", "LinkedList",
  ]
}

function getTopLevels(): PluginEngineTopLevel[] {
  return [
    { label: "println!", insertText: "println!(\"${1}\")", detail: "print line macro", kind: "method" },
    { label: "print!", insertText: "print!(\"${1}\")", detail: "print macro", kind: "method" },
    { label: "format!", insertText: "format!(\"${1}\", ${2:args})", detail: "format macro", kind: "method" },
    { label: "eprintln!", insertText: "eprintln!(\"${1}\")", detail: "stderr print macro", kind: "method" },
    { label: "format_args!", insertText: "format_args!(\"${1}\")", detail: "format args", kind: "method" },
    { label: "vec!", insertText: "vec![${1}]", detail: "vector macro", kind: "method" },
    { label: "vec![]", insertText: "vec![${1}]", detail: "new vector macro", kind: "method" },
    { label: "assert!", insertText: "assert!(${1:cond})", detail: "assert macro", kind: "method" },
    { label: "assert_eq!", insertText: "assert_eq!(${1:left}, ${2:right})", detail: "assert equal macro", kind: "method" },
    { label: "assert_ne!", insertText: "assert_ne!(${1:left}, ${2:right})", detail: "assert not equal macro", kind: "method" },
    { label: "debug_assert!", insertText: "debug_assert!(${1:cond})", detail: "debug assert macro", kind: "method" },
    { label: "panic!", insertText: "panic!(\"${1:msg}\")", detail: "panic macro", kind: "method" },
    { label: "unreachable!", insertText: "unreachable!()", detail: "unreachable macro", kind: "method" },
    { label: "unimplemented!", insertText: "unimplemented!()", detail: "unimplemented macro", kind: "method" },
    { label: "todo!", insertText: "todo!()", detail: "todo macro", kind: "method" },
    { label: "concat!", insertText: "concat!(${1})", detail: "string concatenation macro", kind: "method" },
    { label: "concat_idents!", insertText: "concat_idents!(${1})", detail: "identifier concatenation", kind: "method" },
    { label: "compile_error!", insertText: "compile_error!(\"${1}\")", detail: "compile error macro", kind: "method" },
    { label: "include!", insertText: "include!(\"${1}\")", detail: "include file as string", kind: "method" },
    { label: "include_str!", insertText: "include_str!(\"${1}\")", detail: "include file as str", kind: "method" },
    { label: "include_bytes!", insertText: "include_bytes!(\"${1}\")", detail: "include file as bytes", kind: "method" },
    { label: "stringify!", insertText: "stringify!(${1})", detail: "stringify macro", kind: "method" },
    { label: "dbg!", insertText: "dbg!(${1})", detail: "debug print macro", kind: "method" },
    { label: "fn main", insertText: "fn main() {\n    ${1}\n}", detail: "main function", kind: "snippet" },
    { label: "fn (public)", insertText: "pub fn ${1:name}(${2:params}) -> ${3:ReturnType} {\n    ${4}\n}", detail: "public function", kind: "snippet" },
    { label: "impl Struct", insertText: "impl ${1:Struct} {\n    ${2}\n}", detail: "impl block", kind: "snippet" },
    { label: "impl Trait for Struct", insertText: "impl ${1:Trait} for ${2:Struct} {\n    ${3}\n}", detail: "trait impl", kind: "snippet" },
    { label: "match", insertText: "match ${1:expr} {\n    ${2:pattern} => ${3:result},\n    _ => ${4:default},\n}", detail: "match expression", kind: "snippet" },
    { label: "#[test]", insertText: "#[test]\nfn ${1:test_name}() {\n    ${2}\n}", detail: "test function", kind: "snippet" },
    { label: "#[derive(Debug)]", insertText: "#[derive(Debug)]\nstruct ${1:Name} {\n    ${2}\n}", detail: "derive debug struct", kind: "snippet" },
    { label: "#[derive(Debug, Clone)]", insertText: "#[derive(Debug, Clone)]", detail: "derive Debug + Clone", kind: "snippet" },
    { label: "#[derive(Debug, Clone, PartialEq)]", insertText: "#[derive(Debug, Clone, PartialEq)]", detail: "derive Debug+Clone+PartialEq", kind: "snippet" },
    { label: "Ok()", insertText: "Ok(${1})", detail: "Result::Ok", kind: "snippet" },
    { label: "Err()", insertText: "Err(${1})", detail: "Result::Err", kind: "snippet" },
    { label: "Some()", insertText: "Some(${1})", detail: "Option::Some", kind: "snippet" },
    { label: "None", insertText: "None", detail: "Option::None", kind: "snippet" },
    { label: "if let Some", insertText: "if let Some(${1:x}) = ${2:expr} {\n    ${3}\n}", detail: "if-let Some pattern", kind: "snippet" },
    { label: "if let Ok", insertText: "if let Ok(${1:x}) = ${2:expr} {\n    ${3}\n}", detail: "if-let Ok pattern", kind: "snippet" },
    { label: "if let Err", insertText: "if let Err(${1:e}) = ${2:expr} {\n    ${3}\n}", detail: "if-let Err pattern", kind: "snippet" },
  ]
}

function getImports(): PluginEngineTopLevel[] {
  return [
    { label: "std::collections::HashMap", insertText: "std::collections::HashMap", detail: "hash map", kind: "module" },
    { label: "std::collections::HashSet", insertText: "std::collections::HashSet", detail: "hash set", kind: "module" },
    { label: "std::collections::BTreeMap", insertText: "std::collections::BTreeMap", detail: "B-tree map", kind: "module" },
    { label: "std::collections::BTreeSet", insertText: "std::collections::BTreeSet", detail: "B-tree set", kind: "module" },
    { label: "std::collections::VecDeque", insertText: "std::collections::VecDeque", detail: "double-ended queue", kind: "module" },
    { label: "std::collections::LinkedList", insertText: "std::collections::LinkedList", detail: "linked list", kind: "module" },
    { label: "std::io", insertText: "std::io", detail: "I/O trait", kind: "module" },
    { label: "std::io::Read", insertText: "std::io::Read", detail: "read trait", kind: "module" },
    { label: "std::io::Write", insertText: "std::io::Write", detail: "write trait", kind: "module" },
    { label: "std::io::BufReader", insertText: "std::io::BufReader", detail: "buffered reader", kind: "module" },
    { label: "std::io::BufWriter", insertText: "std::io::BufWriter", detail: "buffered writer", kind: "module" },
    { label: "std::fs", insertText: "std::fs", detail: "filesystem ops", kind: "module" },
    { label: "std::fs::File", insertText: "std::fs::File", detail: "file handle", kind: "module" },
    { label: "std::path::Path", insertText: "std::path::Path", detail: "path", kind: "module" },
    { label: "std::path::PathBuf", insertText: "std::path::PathBuf", detail: "owned path", kind: "module" },
    { label: "std::env", insertText: "std::env", detail: "environment", kind: "module" },
    { label: "std::process::Command", insertText: "std::process::Command", detail: "process command", kind: "module" },
    { label: "std::thread", insertText: "std::thread", detail: "threads", kind: "module" },
    { label: "std::sync::Mutex", insertText: "std::sync::Mutex", detail: "mutex", kind: "module" },
    { label: "std::sync::Arc", insertText: "std::sync::Arc", detail: "atomic reference count", kind: "module" },
    { label: "std::sync::mpsc", insertText: "std::sync::mpsc", detail: "multi-producer channel", kind: "module" },
    { label: "std::time", insertText: "std::time", detail: "time", kind: "module" },
    { label: "std::time::Duration", insertText: "std::time::Duration", detail: "duration", kind: "module" },
    { label: "std::time::Instant", insertText: "std::time::Instant", detail: "instant", kind: "module" },
    { label: "std::net::TcpListener", insertText: "std::net::TcpListener", detail: "TCP listener", kind: "module" },
    { label: "std::net::TcpStream", insertText: "std::net::TcpStream", detail: "TCP stream", kind: "module" },
    { label: "serde::Serialize", insertText: "serde::Serialize", detail: "serialize trait", kind: "module" },
    { label: "serde::Deserialize", insertText: "serde::Deserialize", detail: "deserialize trait", kind: "module" },
    { label: "serde_json", insertText: "serde_json", detail: "JSON for Serde", kind: "module" },
    { label: "tokio", insertText: "tokio", detail: "async runtime", kind: "module" },
  ]
}

function getClasses(): Record<string, unknown> {
  return {
    "String": {
      name: "String", detail: "heap-allocated UTF-8 string",
      implements: [],
      methods: [
        { name: "new", params: "()", returnType: "static String", detail: "empty string" },
        { name: "push", params: "(ch)", returnType: "void", detail: "append char" },
        { name: "push_str", params: "(s)", returnType: "void", detail: "append string slice" },
        { name: "pop", params: "()", returnType: "Option<char>", detail: "remove last char" },
        { name: "len", params: "()", returnType: "usize", detail: "byte length" },
        { name: "is_empty", params: "()", returnType: "bool", detail: "is empty?" },
        { name: "clear", params: "()", returnType: "void", detail: "clear string" },
        { name: "replace", params: "(from, to)", returnType: "String", detail: "replace" },
        { name: "contains", params: "(pattern)", returnType: "bool", detail: "contains?" },
        { name: "starts_with", params: "(pattern)", returnType: "bool", detail: "starts with?" },
        { name: "ends_with", params: "(pattern)", returnType: "bool", detail: "ends with?" },
        { name: "find", params: "(pattern)", returnType: "Option<usize>", detail: "find first" },
        { name: "split", params: "(pattern)", returnType: "Split", detail: "split" },
        { name: "split_whitespace", params: "()", returnType: "SplitWhitespace", detail: "split by whitespace" },
        { name: "trim", params: "()", returnType: "&str", detail: "trim whitespace" },
        { name: "trim_start", params: "()", returnType: "&str", detail: "trim left" },
        { name: "trim_end", params: "()", returnType: "&str", detail: "trim right" },
        { name: "to_lowercase", params: "()", returnType: "String", detail: "to lowercase" },
        { name: "to_uppercase", params: "()", returnType: "String", detail: "to uppercase" },
        { name: "as_str", params: "()", returnType: "&str", detail: "as string slice" },
      ],
    },
    "Vec": {
      name: "Vec", detail: "heap-allocated growable array",
      implements: [],
      methods: [
        { name: "new", params: "()", returnType: "static Vec<T>", detail: "empty vec" },
        { name: "push", params: "(value)", returnType: "void", detail: "append element" },
        { name: "pop", params: "()", returnType: "Option<T>", detail: "remove last" },
        { name: "len", params: "()", returnType: "usize", detail: "element count" },
        { name: "is_empty", params: "()", returnType: "bool", detail: "is empty?" },
        { name: "clear", params: "()", returnType: "void", detail: "clear all" },
        { name: "first", params: "()", returnType: "Option<&T>", detail: "first element" },
        { name: "last", params: "()", returnType: "Option<&T>", detail: "last element" },
        { name: "get", params: "(index)", returnType: "Option<&T>", detail: "get by index" },
        { name: "remove", params: "(index)", returnType: "T", detail: "remove at index" },
        { name: "insert", params: "(index, value)", returnType: "void", detail: "insert at index" },
        { name: "sort", params: "()", returnType: "void", detail: "sort in place" },
        { name: "sort_by", params: "(f)", returnType: "void", detail: "sort by comparator" },
        { name: "reverse", params: "()", returnType: "void", detail: "reverse order" },
        { name: "iter", params: "()", returnType: "Iter<T>", detail: "immutable iterator" },
        { name: "iter_mut", params: "()", returnType: "IterMut<T>", detail: "mutable iterator" },
        { name: "split_off", params: "(at)", returnType: "Vec<T>", detail: "split at index" },
        { name: "retain", params: "(f)", returnType: "void", detail: "retain by predicate" },
        { name: "drain", params: "(range)", returnType: "Drain<T>", detail: "drain range" },
      ],
    },
    "HashMap": {
      name: "HashMap", detail: "key-value hash map",
      implements: [],
      methods: [
        { name: "new", params: "()", returnType: "static HashMap<K,V>", detail: "empty map" },
        { name: "insert", params: "(k, v)", returnType: "Option<V>", detail: "insert key-value" },
        { name: "get", params: "(k)", returnType: "Option<&V>", detail: "get by key" },
        { name: "contains_key", params: "(k)", returnType: "bool", detail: "has key?" },
        { name: "remove", params: "(k)", returnType: "Option<V>", detail: "remove entry" },
        { name: "len", params: "()", returnType: "usize", detail: "entry count" },
        { name: "is_empty", params: "()", returnType: "bool", detail: "is empty?" },
        { name: "clear", params: "()", returnType: "void", detail: "clear all" },
        { name: "iter", params: "()", returnType: "Iter<K,V>", detail: "iterate entries" },
        { name: "keys", params: "()", returnType: "Keys<K,V>", detail: "iterate keys" },
        { name: "values", params: "()", returnType: "Values<K,V>", detail: "iterate values" },
        { name: "values_mut", params: "()", returnType: "ValuesMut<K,V>", detail: "mutable values iter" },
      ],
    },
    "Option": {
      name: "Option", detail: "optional value: Some(T) or None",
      implements: [],
      methods: [
        { name: "is_some", params: "()", returnType: "bool", detail: "is Some?" },
        { name: "is_none", params: "()", returnType: "bool", detail: "is None?" },
        { name: "unwrap", params: "()", returnType: "T", detail: "unwrap (panics if None)" },
        { name: "unwrap_or", params: "(default)", returnType: "T", detail: "unwrap with default" },
        { name: "unwrap_or_else", params: "(f)", returnType: "T", detail: "unwrap with closure" },
        { name: "map", params: "(f)", returnType: "Option<U>", detail: "map value" },
        { name: "and_then", params: "(f)", returnType: "Option<U>", detail: "chain computation" },
        { name: "filter", params: "(predicate)", returnType: "Option<T>", detail: "filter by predicate" },
        { name: "or", params: "(optb)", returnType: "Option<T>", detail: "alternative option" },
        { name: "take", params: "()", returnType: "Option<T>", detail: "take ownership" },
      ],
    },
    "Result": {
      name: "Result", detail: "result: Ok(T) or Err(E)",
      implements: [],
      methods: [
        { name: "is_ok", params: "()", returnType: "bool", detail: "is Ok?" },
        { name: "is_err", params: "()", returnType: "bool", detail: "is Err?" },
        { name: "unwrap", params: "()", returnType: "T", detail: "unwrap (panics if Err)" },
        { name: "unwrap_err", params: "()", returnType: "E", detail: "unwrap error" },
        { name: "unwrap_or", params: "(default)", returnType: "T", detail: "unwrap with default" },
        { name: "map", params: "(f)", returnType: "Result<U,E>", detail: "map Ok value" },
        { name: "map_err", params: "(f)", returnType: "Result<T,F>", detail: "map Err value" },
        { name: "and_then", params: "(f)", returnType: "Result<U,E>", detail: "chain on Ok" },
        { name: "or", params: "(resb)", returnType: "Result<T,E>", detail: "alternative result" },
        { name: "expect", params: "(msg)", returnType: "T", detail: "unwrap with message" },
      ],
    },
    "Iterator": {
      name: "Iterator", detail: "iterator trait",
      implements: [],
      methods: [
        { name: "next", params: "()", returnType: "Option<T>", detail: "next element" },
        { name: "collect", params: "()", returnType: "C", detail: "collect into collection" },
        { name: "map", params: "(f)", returnType: "Map", detail: "map elements" },
        { name: "filter", params: "(predicate)", returnType: "Filter", detail: "filter elements" },
        { name: "filter_map", params: "(f)", returnType: "FilterMap", detail: "filter + map" },
        { name: "flat_map", params: "(f)", returnType: "FlatMap", detail: "flat map" },
        { name: "fold", params: "(init, f)", returnType: "B", detail: "fold/reduce" },
        { name: "take", params: "(n)", returnType: "Take", detail: "take first n" },
        { name: "skip", params: "(n)", returnType: "Skip", detail: "skip first n" },
        { name: "enumerate", params: "()", returnType: "Enumerate", detail: "add index" },
        { name: "zip", params: "(other)", returnType: "Zip", detail: "zip two iterators" },
        { name: "chain", params: "(other)", returnType: "Chain", detail: "chain iterators" },
        { name: "any", params: "(predicate)", returnType: "bool", detail: "any matches?" },
        { name: "all", params: "(predicate)", returnType: "bool", detail: "all match?" },
        { name: "rev", params: "()", returnType: "Rev", detail: "reverse" },
        { name: "count", params: "()", returnType: "usize", detail: "count elements" },
        { name: "nth", params: "(n)", returnType: "Option<T>", detail: "nth element" },
        { name: "last", params: "()", returnType: "Option<T>", detail: "last element" },
        { name: "find", params: "(predicate)", returnType: "Option<T>", detail: "find matching" },
        { name: "position", params: "(predicate)", returnType: "Option<usize>", detail: "find position" },
      ],
    },
  }
}