export type SettingScope = "application" | "user" | "workspace" | "folder" | "language"
export type SettingStatus = "ready" | "planned" | "requires-vscode-service"
export type SettingControl =
  | "text"
  | "password"
  | "number"
  | "boolean"
  | "select"
  | "textarea"
  | "json"
  | "button"

export interface SettingOption {
  label: string
  value: string | number | boolean
}

export interface SettingDefinition<T = unknown> {
  key: string
  vscodeKey?: string
  title: string
  description: string
  group: string
  scope: SettingScope[]
  control: SettingControl
  defaultValue: T
  options?: SettingOption[]
  status?: SettingStatus
}

export interface SettingGroupDefinition {
  id: string
  title: string
  description: string
}

export const SETTING_GROUPS: SettingGroupDefinition[] = [
  { id: "general", title: "通用", description: "语言、启动行为和基础工作流。" },
  { id: "appearance", title: "外观", description: "主题、布局和工作台视觉设置。" },
  { id: "editor", title: "编辑器", description: "Monaco 与 VS Code 兼容编辑设置。" },
  { id: "files", title: "文件", description: "保存、编码、换行符和排除规则。" },
  { id: "explorer", title: "资源管理器", description: "Explorer 排序、文件操作和 VS Code 兼容行为。" },
  { id: "search", title: "搜索", description: "搜索范围、忽略规则和位置。" },
  { id: "terminal", title: "终端", description: "终端 profile、字体和滚动缓冲。" },
  { id: "source-control", title: "源代码管理", description: "Git 与提交相关设置。" },
  { id: "extensions", title: "扩展", description: "扩展市场、VSIX 和扩展状态。" },
  { id: "keyboard", title: "快捷键", description: "快捷键 UI 与 keybindings.json 兼容。" },
  { id: "languages", title: "语言", description: "运行时、格式化器和语言级覆盖。" },
  { id: "ai-models", title: "智能模型", description: "供应商、模型、API 密钥和生成参数。" },
  { id: "agent", title: "智能体", description: "智能体模式、审批和命令策略。" },
  { id: "rules-memory", title: "规则与记忆", description: "用户规则、项目规则和记忆。" },
  { id: "indexing", title: "索引与上下文", description: "代码索引、docs、web search 和 embedding。" },
  { id: "privacy", title: "隐私", description: "隐私模式、本地优先和敏感内容保护。" },
  { id: "workspace", title: "工作区", description: "当前项目的覆盖设置。" },
  { id: "advanced", title: "高级", description: "设置 JSON、导入导出和诊断。" },
]

export const SETTINGS_SCHEMA: SettingDefinition[] = [
  {
    key: "codek.locale",
    title: "界面语言",
    description: "控制 Codek 界面显示语言，保留 VS Code、Cursor、API 等专有名词。",
    group: "general",
    scope: ["application", "user"],
    control: "select",
    defaultValue: "zh",
    options: [
      { label: "简体中文", value: "zh" },
      { label: "English", value: "en" },
      { label: "繁體中文", value: "zhTw" },
    ],
  },
  {
    key: "window.restoreWindows",
    title: "启动时恢复窗口",
    description: "控制启动时是否恢复上次打开的工作区窗口。",
    group: "general",
    scope: ["application", "user"],
    control: "select",
    defaultValue: "all",
    options: [
      { label: "恢复全部", value: "all" },
      { label: "仅恢复文件夹", value: "folders" },
      { label: "不恢复", value: "none" },
    ],
  },
  {
    key: "security.workspace.trust.enabled",
    title: "启用工作区信任",
    description: "控制是否启用 VS Code 兼容的工作区信任门控。",
    group: "workspace",
    scope: ["application", "user"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "security.workspace.trust.startupPrompt",
    title: "启动时提示工作区信任",
    description: "控制受限工作区启动时是否显示工作区信任提示。",
    group: "workspace",
    scope: ["application", "user"],
    control: "select",
    defaultValue: "once",
    options: [
      { label: "每个工作区一次", value: "once" },
      { label: "始终", value: "always" },
      { label: "从不", value: "never" },
    ],
  },
  {
    key: "security.workspace.trust.untrustedFiles",
    title: "不受信任文件处理",
    description: "控制受信任工作区打开外部不受信任文件时的处理策略。",
    group: "workspace",
    scope: ["application", "user"],
    control: "select",
    defaultValue: "prompt",
    options: [
      { label: "提示", value: "prompt" },
      { label: "直接打开", value: "open" },
      { label: "新窗口打开", value: "newWindow" },
    ],
  },
  {
    key: "security.workspace.trust.banner",
    title: "显示受限模式横幅",
    description: "控制受限模式下是否显示工作区信任横幅。",
    group: "workspace",
    scope: ["application", "user"],
    control: "select",
    defaultValue: "untilDismissed",
    options: [
      { label: "直到关闭", value: "untilDismissed" },
      { label: "始终", value: "always" },
      { label: "从不", value: "never" },
    ],
  },
  {
    key: "security.workspace.trust.emptyWindow",
    title: "信任空窗口",
    description: "控制没有文件夹或工作区的空窗口是否默认受信任。",
    group: "workspace",
    scope: ["application", "user"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "update.mode",
    title: "更新模式",
    description: "控制 Codek 更新检查策略；桌面更新接口可用时会按该策略触发检查或下载。",
    group: "general",
    scope: ["application", "user"],
    control: "select",
    defaultValue: "manual",
    options: [
      { label: "手动", value: "manual" },
      { label: "自动检查", value: "check" },
      { label: "自动下载", value: "download" },
    ],
  },
  {
    key: "workbench.colorTheme",
    title: "颜色主题",
    description: "控制 Codek 工作台和 Monaco 编辑器的颜色主题。",
    group: "appearance",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "dark",
    options: [
      { label: "深色", value: "dark" },
      { label: "浅色", value: "light" },
    ],
  },
  {
    key: "workbench.iconTheme",
    title: "图标主题",
    description: "控制文件树和工作台使用的图标主题。",
    group: "appearance",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "vs-seti",
    options: [
      { label: "VS Code Seti", value: "vs-seti" },
      { label: "Codek 默认", value: "codek-default" },
      { label: "极简", value: "minimal" },
      { label: "单色", value: "monochrome" },
    ],
  },
  {
    key: "workbench.productIconTheme",
    title: "产品图标主题",
    description: "控制活动栏、面板和命令等工作台产品图标主题；当前默认对齐 VS Code 的内置产品图标。",
    group: "appearance",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "Default",
    options: [
      { label: "默认", value: "Default" },
    ],
  },
  {
    key: "workbench.activityBar.visible",
    title: "显示活动栏",
    description: "控制工作台活动栏是否显示。",
    group: "appearance",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "workbench.statusBar.visible",
    title: "显示状态栏",
    description: "控制底部状态栏是否显示。",
    group: "appearance",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "workbench.sideBar.location",
    title: "侧边栏位置",
    description: "控制侧边栏显示在左侧或右侧。",
    group: "appearance",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "left",
    options: [
      { label: "左侧", value: "left" },
      { label: "右侧", value: "right" },
    ],
  },
  {
    key: "workbench.panel.defaultLocation",
    title: "面板位置",
    description: "控制终端、问题等面板的默认位置。",
    group: "appearance",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "bottom",
    options: [
      { label: "底部", value: "bottom" },
      { label: "右侧", value: "right" },
      { label: "左侧", value: "left" },
    ],
  },
  {
    key: "editor.fontSize",
    title: "编辑器字号",
    description: "控制编辑器正文的字体大小。",
    group: "editor",
    scope: ["user", "workspace", "language"],
    control: "number",
    defaultValue: 14,
  },
  {
    key: "editor.fontFamily",
    title: "编辑器字体",
    description: "控制编辑器使用的字体族。",
    group: "editor",
    scope: ["user", "workspace", "language"],
    control: "text",
    defaultValue: "'JetBrains Mono', 'Fira Code', monospace",
  },
  {
    key: "editor.tabSize",
    title: "Tab 大小",
    description: "一个 Tab 等于多少个空格。",
    group: "editor",
    scope: ["user", "workspace", "language"],
    control: "number",
    defaultValue: 2,
  },
  {
    key: "editor.insertSpaces",
    title: "插入空格",
    description: "按 Tab 时插入空格而不是制表符。",
    group: "editor",
    scope: ["user", "workspace", "language"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "editor.wordWrap",
    title: "自动换行",
    description: "控制长行是否在编辑器宽度内换行。",
    group: "editor",
    scope: ["user", "workspace", "language"],
    control: "select",
    defaultValue: "off",
    options: [
      { label: "关闭", value: "off" },
      { label: "开启", value: "on" },
      { label: "按列换行", value: "wordWrapColumn" },
    ],
  },
  {
    key: "editor.minimap.enabled",
    title: "显示 minimap",
    description: "控制编辑器右侧代码缩略图。",
    group: "editor",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "editor.lineNumbers",
    title: "显示行号",
    description: "控制编辑器是否显示行号。",
    group: "editor",
    scope: ["user", "workspace", "language"],
    control: "select",
    defaultValue: "on",
    options: [
      { label: "开启", value: "on" },
      { label: "关闭", value: "off" },
      { label: "相对行号", value: "relative" },
    ],
  },
  {
    key: "editor.renderWhitespace",
    title: "显示空白字符",
    description: "控制空格和 Tab 的可视化显示。",
    group: "editor",
    scope: ["user", "workspace", "language"],
    control: "select",
    defaultValue: "selection",
    options: [
      { label: "选中时显示", value: "selection" },
      { label: "全部显示", value: "all" },
      { label: "不显示", value: "none" },
    ],
  },
  {
    key: "editor.bracketPairColorization.enabled",
    title: "括号对着色",
    description: "为匹配的括号使用不同颜色。",
    group: "editor",
    scope: ["user", "workspace", "language"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "editor.formatOnSave",
    title: "保存时格式化",
    description: "保存文件时自动格式化。",
    group: "editor",
    scope: ["user", "workspace", "language"],
    control: "boolean",
    defaultValue: false,
  },
  {
    key: "editor.formatOnPaste",
    title: "粘贴时格式化",
    description: "粘贴代码后自动格式化。",
    group: "editor",
    scope: ["user", "workspace", "language"],
    control: "boolean",
    defaultValue: false,
  },
  {
    key: "files.autoSave",
    title: "自动保存",
    description: "控制文件自动保存策略。",
    group: "files",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "off",
    options: [
      { label: "关闭", value: "off" },
      { label: "延迟后保存", value: "afterDelay" },
      { label: "焦点变化时保存", value: "onFocusChange" },
    ],
  },
  {
    key: "files.autoSaveDelay",
    title: "自动保存延迟",
    description: "自动保存触发前等待的毫秒数。",
    group: "files",
    scope: ["user", "workspace"],
    control: "number",
    defaultValue: 1000,
  },
  {
    key: "files.encoding",
    title: "文件编码",
    description: "新文件和读取文件时使用的默认编码。",
    group: "files",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "utf-8",
    options: [
      { label: "UTF-8", value: "utf-8" },
      { label: "GBK", value: "gbk" },
    ],
  },
  {
    key: "files.eol",
    title: "换行符",
    description: "控制保存文件时使用的换行符。",
    group: "files",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "auto",
    options: [
      { label: "自动", value: "auto" },
      { label: "LF", value: "lf" },
      { label: "CRLF", value: "crlf" },
    ],
  },
  {
    key: "files.trimTrailingWhitespace",
    title: "保存时清理行尾空白",
    description: "保存文件时删除行尾多余空白。",
    group: "files",
    scope: ["user", "workspace", "language"],
    control: "boolean",
    defaultValue: false,
  },
  {
    key: "files.insertFinalNewline",
    title: "插入最终换行",
    description: "保存文件时确保末尾有换行符。",
    group: "files",
    scope: ["user", "workspace", "language"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "files.exclude",
    title: "文件排除规则",
    description: "从文件树中隐藏的 glob 规则。",
    group: "files",
    scope: ["user", "workspace"],
    control: "json",
    defaultValue: ["node_modules", ".git", "dist", "build", "__pycache__"],
  },
  {
    key: "search.include",
    title: "搜索包含规则",
    description: "搜索时包含的 glob 规则。",
    group: "search",
    scope: ["user", "workspace"],
    control: "json",
    defaultValue: ["*"],
  },
  {
    key: "search.exclude",
    title: "搜索排除规则",
    description: "搜索时排除的 glob 规则。",
    group: "search",
    scope: ["user", "workspace"],
    control: "json",
    defaultValue: ["node_modules", ".git", "dist", "build"],
  },
  {
    key: "terminal.integrated.defaultProfile.windows",
    title: "Windows 默认终端配置",
    description: "Windows 下新终端默认使用的 shell 配置。",
    group: "terminal",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "PowerShell",
    options: [
      { label: "PowerShell", value: "PowerShell" },
      { label: "Command Prompt", value: "Command Prompt" },
      { label: "Git Bash", value: "Git Bash" },
    ],
  },
  {
    key: "terminal.integrated.fontFamily",
    title: "终端字体",
    description: "终端使用的字体族。",
    group: "terminal",
    scope: ["user", "workspace"],
    control: "text",
    defaultValue: "Consolas, monospace",
  },
  {
    key: "terminal.integrated.fontSize",
    title: "终端字号",
    description: "终端正文的字体大小。",
    group: "terminal",
    scope: ["user", "workspace"],
    control: "number",
    defaultValue: 13,
  },
  {
    key: "terminal.integrated.scrollback",
    title: "终端滚动缓冲",
    description: "终端保留的历史行数。",
    group: "terminal",
    scope: ["user", "workspace"],
    control: "number",
    defaultValue: 1000,
  },
  {
    key: "git.enabled",
    title: "启用 Git",
    description: "启用源代码管理相关能力。",
    group: "source-control",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "git.autofetch",
    title: "自动 Fetch",
    description: "自动从远端拉取 Git 状态。",
    group: "source-control",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "git.autoStage",
    title: "自动暂存",
    description: "提交前自动暂存变更。",
    group: "source-control",
    scope: ["workspace"],
    control: "boolean",
    defaultValue: false,
  },
  {
    key: "extensions.autoUpdate",
    title: "自动更新扩展",
    description: "自动更新已安装扩展。",
    group: "extensions",
    scope: ["user"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "extensions.ignoreRecommendations",
    title: "忽略扩展推荐",
    description: "不显示工作区扩展推荐。",
    group: "extensions",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: false,
  },
  {
    key: "codek.ai.provider",
    title: "模型供应商",
    description: "聊天和智能体默认使用的模型供应商。",
    group: "ai-models",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "ollama",
    options: [
      { label: "Ollama", value: "ollama" },
      { label: "OpenAI Compatible", value: "openai-compatible" },
      { label: "Anthropic", value: "anthropic" },
      { label: "codex-shared", value: "codex-shared" },
    ],
  },
  {
    key: "codek.ai.model",
    title: "智能模型",
    description: "默认聊天模型。",
    group: "ai-models",
    scope: ["user", "workspace"],
    control: "text",
    defaultValue: "",
  },
  {
    key: "codek.ai.baseUrl",
    title: "接口地址",
    description: "OpenAI Compatible 等供应商的接口地址。",
    group: "ai-models",
    scope: ["user"],
    control: "text",
    defaultValue: "",
  },
  {
    key: "codek.ai.temperature",
    title: "Temperature",
    description: "控制模型输出随机性。",
    group: "ai-models",
    scope: ["user", "workspace"],
    control: "number",
    defaultValue: 0.7,
  },
  {
    key: "codek.ai.topP",
    title: "Top P",
    description: "控制 nucleus sampling 范围。",
    group: "ai-models",
    scope: ["user", "workspace"],
    control: "number",
    defaultValue: 0.9,
  },
  {
    key: "codek.ai.maxTokens",
    title: "Max Tokens",
    description: "单次输出的最大 token 数。",
    group: "ai-models",
    scope: ["user", "workspace"],
    control: "number",
    defaultValue: 4096,
  },
  {
    key: "codek.ai.completionModel",
    title: "补全模型",
    description: "行内补全使用的模型，为空时使用聊天模型。",
    group: "ai-models",
    scope: ["user", "workspace"],
    control: "text",
    defaultValue: "",
  },
  {
    key: "codek.languages.jdkVersion",
    title: "JDK 版本",
    description: "Java 语言服务使用的目标 JDK 版本。",
    group: "languages",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "17",
    options: [
      { label: "JDK 8", value: "8" },
      { label: "JDK 11", value: "11" },
      { label: "JDK 17", value: "17" },
      { label: "JDK 21", value: "21" },
      { label: "JDK 22", value: "22" },
      { label: "JDK 23", value: "23" },
    ],
  },
  {
    key: "codek.languages.jdkPath",
    title: "JDK 路径",
    description: "自定义 JDK 安装路径。",
    group: "languages",
    scope: ["user", "workspace"],
    control: "text",
    defaultValue: "",
  },
  {
    key: "codek.languages.pythonPath",
    title: "Python 路径",
    description: "自定义 Python 解释器路径。",
    group: "languages",
    scope: ["user", "workspace"],
    control: "text",
    defaultValue: "",
  },
  {
    key: "codek.languages.enabled",
    title: "启用语言",
    description: "启用语言服务和代码补全的语言 ID 列表。",
    group: "languages",
    scope: ["user", "workspace"],
    control: "json",
    defaultValue: [
      "java",
      "python",
      "javascript",
      "typescript",
      "html",
      "css",
      "go",
      "rust",
      "cpp",
      "csharp",
      "kotlin",
      "php",
      "ruby",
      "dart",
    ],
  },
  {
    key: "codek.privacy.enabled",
    title: "隐私模式",
    description: "开启后阻止云端供应商，优先使用本地模型。",
    group: "privacy",
    scope: ["application", "user"],
    control: "boolean",
    defaultValue: false,
  },
  {
    key: "telemetry.telemetryLevel",
    title: "遥测级别",
    description: "控制产品遥测和诊断事件采集范围；事件会保存在本地诊断缓存中。",
    group: "privacy",
    scope: ["application", "user"],
    control: "select",
    defaultValue: "off",
    options: [
      { label: "关闭", value: "off" },
      { label: "错误", value: "error" },
      { label: "基础", value: "crash" },
      { label: "全部", value: "all" },
    ],
  },
  {
    key: "codek.privacy.redactLogs",
    title: "日志脱敏",
    description: "在日志、诊断和智能体轨迹中隐藏 API 密钥、Token、路径等敏感内容。",
    group: "privacy",
    scope: ["application", "user", "workspace"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "codek.privacy.sensitiveFilePatterns",
    title: "敏感文件排除",
    description: "禁止自动索引或发送给模型的敏感文件 glob 列表。",
    group: "privacy",
    scope: ["user", "workspace"],
    control: "json",
    defaultValue: [
      ".env",
      ".env.*",
      "*.pem",
      "*.key",
      "*.p12",
      "*.pfx",
      "*.jks",
      "*.keystore",
    ],
  },
  {
    key: "codek.webSearch.provider",
    title: "Web 搜索供应商",
    description: "用于 @web 上下文的搜索供应商。",
    group: "indexing",
    scope: ["user"],
    control: "select",
    defaultValue: "searxng",
    options: [
      { label: "SearXNG", value: "searxng" },
      { label: "SerpAPI", value: "serpapi" },
      { label: "Bing", value: "bing" },
    ],
  },
  {
    key: "codek.webSearch.baseUrl",
    title: "Web 搜索接口地址",
    description: "搜索服务基础地址。",
    group: "indexing",
    scope: ["user"],
    control: "text",
    defaultValue: "http://localhost:8888",
  },
  {
    key: "codek.webSearch.apiKey",
    title: "Web 搜索 API 密钥",
    description: "SerpAPI、Bing 等搜索供应商使用的 API 密钥。",
    group: "indexing",
    scope: ["user"],
    control: "password",
    defaultValue: "",
  },
  {
    key: "codek.agent.approvalMode",
    title: "智能体审批模式",
    description: "控制智能体执行命令和写文件前是否需要确认。",
    group: "agent",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "ask",
    options: [
      { label: "每次询问", value: "ask" },
      { label: "工作区内自动", value: "workspace-auto" },
      { label: "只读", value: "read-only" },
    ],
  },
  {
    key: "codek.agent.terminalPolicy",
    title: "智能体终端策略",
    description: "控制智能体可以自动运行哪些终端命令。",
    group: "agent",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "ask",
    options: [
      { label: "每次询问", value: "ask" },
      { label: "允许安全命令", value: "safe-only" },
      { label: "禁止运行", value: "disabled" },
    ],
  },
  {
    key: "codek.agent.qualityGateCommands",
    title: "质量门命令",
    description: "智能体补丁被确认应用后自动运行的验证命令列表，例如 typecheck、test、build 或 lint。",
    group: "agent",
    scope: ["workspace"],
    control: "json",
    defaultValue: [],
  },
  {
    key: "codek.rules.enabled",
    title: "启用规则",
    description: "启用后读取项目中的 .codek/rules.md 和 .codek/rules/*.md，作为智能体上下文规则。",
    group: "rules-memory",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "codek.rules.cursorCompat",
    title: "兼容 Cursor 规则目录",
    description: "启用后同时读取 .cursor/rules.md 和 .cursor/rules/*.md，用于迁移 Cursor 项目规则。",
    group: "rules-memory",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: false,
  },
  {
    key: "codek.memory.enabled",
    title: "启用智能体记忆",
    description: "启用后智能体会读取当前记忆供应商并记录偏好、模式、错误、验证和工具摘要。",
    group: "rules-memory",
    scope: ["user"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "codek.memory.provider",
    title: "记忆供应商",
    description: "选择智能体记忆后端；本机记忆服务为可选本地服务，不会自动安装或启动。",
    group: "rules-memory",
    scope: ["user"],
    control: "select",
    defaultValue: "local",
    options: [
      { label: "本地", value: "local" },
      { label: "本机记忆服务", value: "agentmemory" },
    ],
  },
  {
    key: "codek.memory.agentmemory.baseUrl",
    title: "本机记忆服务地址",
    description: "本机记忆服务 REST 地址；v1 只允许 localhost / 127.0.0.1。",
    group: "rules-memory",
    scope: ["user"],
    control: "text",
    defaultValue: "http://127.0.0.1:3111",
  },
  {
    key: "codek.memory.agentmemory.timeoutMs",
    title: "本机记忆服务超时",
    description: "调用本机记忆服务 REST 接口的超时时间，单位毫秒。",
    group: "rules-memory",
    scope: ["user"],
    control: "number",
    defaultValue: 5000,
  },
  {
    key: "codek.memory.agentmemory.authHeader",
    title: "本机记忆服务授权头",
    description: "可选 Authorization header 值；默认留空。v1 仍只允许连接本机记忆服务。",
    group: "rules-memory",
    scope: ["user"],
    control: "password",
    defaultValue: "",
  },
  {
    key: "codek.memory.agentmemory.fallbackToLocal",
    title: "本机记忆服务不可用时回退",
    description: "本机记忆服务连接失败时自动退回本地记忆，不阻断智能体任务。",
    group: "rules-memory",
    scope: ["user"],
    control: "boolean",
    defaultValue: true,
  },
  {
    key: "codek.memory.includeToolOutputs",
    title: "保存工具输出摘要",
    description: "默认关闭；开启后只保存脱敏和裁剪后的 stdout/stderr 摘要，不保存完整输出或文件内容。",
    group: "rules-memory",
    scope: ["user"],
    control: "boolean",
    defaultValue: false,
  },
  {
    key: "codek.memory.maxEntriesPerType",
    title: "每类记忆数量上限",
    description: "控制每类智能体记忆保留数量，超过上限后按时间裁剪旧记录。",
    group: "rules-memory",
    scope: ["user"],
    control: "number",
    defaultValue: 50,
  },
  {
    key: "codek.orchestration.ruflo.enabled",
    title: "Ruflo Adapter",
    description: "实验性 Ruflo 外部 adapter 开关，默认关闭；关闭时不会调用 Ruflo 或创建 .claude 目录。",
    group: "agent",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: false,
  },
  {
    key: "codek.orchestration.ruflo.mode",
    title: "Ruflo 模式",
    description: "Ruflo adapter 预留模式；v1 默认 disabled，不进入主编排流程。",
    group: "agent",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "disabled",
    options: [
      { label: "Disabled", value: "disabled" },
      { label: "External CLI", value: "external-cli" },
    ],
  },
  {
    key: "codek.orchestration.ruflo.command",
    title: "Ruflo 命令",
    description: "实验 adapter 需要时使用的 Ruflo CLI 命令；默认不会执行。",
    group: "agent",
    scope: ["user", "workspace"],
    control: "text",
    defaultValue: "npx ruflo@latest",
  },
  {
    key: "explorer.sortOrder",
    title: "资源管理器排序",
    description: "控制资源管理器中文件和文件夹的排序方式，兼容 VS Code explorer.sortOrder。",
    group: "explorer",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "default",
    options: [
      { label: "默认", value: "default" },
      { label: "混合", value: "mixed" },
      { label: "文件优先", value: "filesFirst" },
      { label: "类型", value: "type" },
      { label: "修改时间", value: "modified" },
      { label: "文件夹嵌套文件", value: "foldersNestsFiles" },
    ],
  },
  {
    key: "explorer.sortOrderLexicographicOptions",
    title: "资源管理器字典序",
    description: "控制资源管理器排序的字典序策略，兼容 VS Code explorer.sortOrderLexicographicOptions。",
    group: "explorer",
    scope: ["user", "workspace"],
    control: "select",
    defaultValue: "default",
    options: [
      { label: "默认", value: "default" },
      { label: "大写优先", value: "upper" },
      { label: "小写优先", value: "lower" },
      { label: "Unicode", value: "unicode" },
    ],
  },
  {
    key: "explorer.sortOrderReverse",
    title: "资源管理器反向排序",
    description: "启用后反转资源管理器排序方向，兼容 VS Code Explorer FileSorter reverse 配置。",
    group: "explorer",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: false,
  },
  {
    key: "codek.indexing.enabled",
    title: "代码库索引",
    description: "启用代码库索引以改善上下文检索。",
    group: "indexing",
    scope: ["user", "workspace"],
    control: "boolean",
    defaultValue: true,
  },
]

export function getSettingDefinition(key: string): SettingDefinition | undefined {
  return SETTINGS_SCHEMA.find((setting) => setting.key === key || setting.vscodeKey === key)
}

export function getSettingsByGroup(group: string): SettingDefinition[] {
  return SETTINGS_SCHEMA.filter((setting) => setting.group === group)
}

export function getDefaultSettings(): Record<string, unknown> {
  return Object.fromEntries(SETTINGS_SCHEMA.map((setting) => [setting.key, setting.defaultValue]))
}
