import type { MarketplaceEntry, MarketplaceFilter } from "./types"

const MARKETPLACE_DATA: MarketplaceEntry[] = [
  {
    id: "codek-java-intellisense",
    name: "codek-java",
    displayName: "Java IntelliSense",
    version: "2.1.0",
    publisher: "Codek Team",
    description: "IDEA 级 Java 代码补全。基于本地 JDK 索引提供类/方法/字段智能补全，支持 JDK 8/11/17/21 版本感知 API，包含完整标准库（String/List/Map/Stream/Optional/HttpClient 等）。",
    icon: "JV",
    keywords: ["java", "intellisense", "completion", "jdk", "standard-library", "snippets"],
    categories: ["languages"],
    language: "java",
    languages: ["java"],
    jdkVersionMin: "8",
    rating: 4.9,
    ratingCount: 2340,
    downloads: 15280,
    trendingDaily: 230,
    size: 42 * 1024,
    sizeLabel: "42 KB",
    updatedAt: "2026-05-15",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-java-intellisense",
    license: "MIT",
  },
  {
    id: "codek-python-intellisense",
    name: "codek-python",
    displayName: "Python IntelliSense",
    version: "2.0.0",
    publisher: "Codek Team",
    description: "Python 代码补全。str/list/dict/set/tuple 完整方法链提示，os/sys/json/re/math/random/datetime/pathlib 标准库，类型注解 + dataclass 支持，代码片段。",
    icon: "PY",
    keywords: ["python", "intellisense", "completion", "standard-library", "type-hints"],
    categories: ["languages"],
    language: "python",
    languages: ["python"],
    rating: 4.8,
    ratingCount: 1890,
    downloads: 12840,
    trendingDaily: 180,
    size: 38 * 1024,
    sizeLabel: "38 KB",
    updatedAt: "2026-05-12",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-python-intellisense",
    license: "MIT",
  },
  {
    id: "codek-go-intellisense",
    name: "codek-go",
    displayName: "Go IntelliSense",
    version: "1.1.0",
    publisher: "Codek Team",
    description: "Go 语言代码补全。fmt/net/http/strings/strconv/os/io/sync/context 标准库方法提示，go/defer/chan/select 语言特性补全，interface/struct 代码片段。",
    icon: "GO",
    keywords: ["go", "golang", "intellisense", "completion", "standard-library"],
    categories: ["languages"],
    language: "go",
    languages: ["go"],
    rating: 4.6,
    ratingCount: 1120,
    downloads: 8920,
    trendingDaily: 95,
    size: 22 * 1024,
    sizeLabel: "22 KB",
    updatedAt: "2026-05-10",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-go-intellisense",
    license: "MIT",
  },
  {
    id: "codek-cpp-intellisense",
    name: "codek-cpp",
    displayName: "C/C++ IntelliSense",
    version: "1.0.1",
    publisher: "Codek Team",
    description: "C/C++ 代码补全。STL 容器（vector/map/set/string/queue）、算法（sort/find/transform）、iostream/fstream 标准库，printf/scanf/malloc C 标准函数。",
    icon: "CP",
    keywords: ["c", "cpp", "c++", "intellisense", "completion", "stl", "standard-library"],
    categories: ["languages"],
    language: "cpp",
    languages: ["c", "cpp"],
    rating: 4.4,
    ratingCount: 850,
    downloads: 6730,
    trendingDaily: 72,
    size: 24 * 1024,
    sizeLabel: "24 KB",
    updatedAt: "2026-05-08",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-cpp-intellisense",
    license: "MIT",
  },
  {
    id: "codek-rust-intellisense",
    name: "codek-rust",
    displayName: "Rust IntelliSense",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Rust 代码补全。Vec/String/HashMap/Option/Result/BTreeMap 标准库，println!/format!/match/impl/trait/enum 语言特性，所有权/借用标注提示。",
    icon: "RS",
    keywords: ["rust", "intellisense", "completion", "cargo", "standard-library"],
    categories: ["languages"],
    language: "rust",
    languages: ["rust"],
    rating: 4.5,
    ratingCount: 680,
    downloads: 5120,
    trendingDaily: 65,
    size: 20 * 1024,
    sizeLabel: "20 KB",
    updatedAt: "2026-05-05",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-rust-intellisense",
    license: "MIT",
  },
  {
    id: "codek-typescript-intellisense",
    name: "codek-typescript",
    displayName: "TypeScript/JavaScript IntelliSense",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "TypeScript/JavaScript 完整 IntelliSense（内置 Monaco Worker）。LSP 级别的类型检查、悬停提示、跳转定义和智能补全。",
    icon: "TS",
    keywords: ["typescript", "javascript", "intellisense", "completion", "lsp"],
    categories: ["languages"],
    language: "typescript",
    languages: ["typescript", "javascript", "jsx", "tsx"],
    rating: 5.0,
    ratingCount: 3200,
    downloads: 21000,
    trendingDaily: 400,
    size: 2 * 1024,
    sizeLabel: "2 KB",
    updatedAt: "2026-05-18",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-typescript-intellisense",
    license: "MIT",
  },
  {
    id: "codek-spring-boot",
    name: "codek-spring-boot",
    displayName: "Spring Boot Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Spring Boot 框架支持。@GetMapping/@Service/@Autowired 等注解补全，application.properties/YAML 智能提示，常用 Spring 组件代码片段。",
    icon: "SB",
    keywords: ["spring", "spring-boot", "java", "framework"],
    categories: ["frameworks"],
    language: "java",
    languages: ["java"],
    rating: 4.7,
    ratingCount: 1240,
    downloads: 9450,
    trendingDaily: 110,
    size: 28 * 1024,
    sizeLabel: "28 KB",
    updatedAt: "2026-05-01",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-spring-boot",
    license: "MIT",
  },
  {
    id: "codek-django",
    name: "codek-django",
    displayName: "Django Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Django 框架支持。models/views/urls/forms/admin 智能补全，ORM 查询提示，模板变量补全，管理命令片段。",
    icon: "DJ",
    keywords: ["django", "python", "framework", "orm"],
    categories: ["frameworks"],
    language: "python",
    languages: ["python"],
    rating: 4.3,
    ratingCount: 720,
    downloads: 6210,
    trendingDaily: 48,
    size: 24 * 1024,
    sizeLabel: "24 KB",
    updatedAt: "2026-04-28",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-django",
    license: "MIT",
  },
  {
    id: "codek-junit",
    name: "codek-junit",
    displayName: "JUnit 5 Test Support",
    version: "1.1.0",
    publisher: "Codek Team",
    description: "JUnit 5 测试框架支持。@Test/@BeforeEach/@ParameterizedTest 补全，assertThat/assertEquals 代码片段，参数化测试模板。",
    icon: "JT",
    keywords: ["junit", "testing", "java"],
    categories: ["tools"],
    language: "java",
    languages: ["java"],
    rating: 4.5,
    ratingCount: 910,
    downloads: 7800,
    trendingDaily: 85,
    size: 10 * 1024,
    sizeLabel: "10 KB",
    updatedAt: "2026-04-25",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-junit",
    license: "MIT",
  },
  {
    id: "codek-pytest",
    name: "codek-pytest",
    displayName: "pytest Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "pytest 测试框架支持。fixture/parametrize/mark 补全，assert 增强提示，conftest.py 模板，测试用例代码片段。",
    icon: "PT",
    keywords: ["pytest", "testing", "python"],
    categories: ["tools"],
    language: "python",
    languages: ["python"],
    rating: 4.4,
    ratingCount: 580,
    downloads: 5400,
    trendingDaily: 52,
    size: 12 * 1024,
    sizeLabel: "12 KB",
    updatedAt: "2026-04-22",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-pytest",
    license: "MIT",
  },
  {
    id: "codek-maven",
    name: "codek-maven",
    displayName: "Maven pom.xml Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Maven pom.xml 支持。依赖坐标自动补全，常用插件片段，仓库配置提示，properties/ profiles 智能提示。",
    icon: "MV",
    keywords: ["maven", "pom", "xml", "java", "build"],
    categories: ["tools"],
    language: "xml",
    languages: ["xml"],
    rating: 4.6,
    ratingCount: 780,
    downloads: 8200,
    trendingDaily: 90,
    size: 15 * 1024,
    sizeLabel: "15 KB",
    updatedAt: "2026-04-20",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-maven",
    license: "MIT",
  },
  {
    id: "codek-git-commit",
    name: "codek-git-commit",
    displayName: "Git Commit Helper",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Conventional Commits 提交规范辅助。feat/fix/refactor 等类型补全，scope 提示，commit message 模板，emoji 前缀支持。",
    icon: "GT",
    keywords: ["git", "commit", "conventional-commits"],
    categories: ["tools"],
    language: "markdown",
    languages: ["markdown", "plaintext"],
    rating: 4.2,
    ratingCount: 420,
    downloads: 4300,
    trendingDaily: 35,
    size: 6 * 1024,
    sizeLabel: "6 KB",
    updatedAt: "2026-04-18",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-git-commit",
    license: "MIT",
  },
  {
    id: "codek-docker",
    name: "codek-docker",
    displayName: "Docker Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Dockerfile 和 docker-compose.yml 支持。FROM/RUN/COPY 等指令补全，镜像名和标签提示，常用 Dockerfile 模板。",
    icon: "DK",
    keywords: ["docker", "container", "dockerfile", "compose"],
    categories: ["tools"],
    language: "dockerfile",
    languages: ["dockerfile", "yaml"],
    rating: 4.3,
    ratingCount: 640,
    downloads: 6100,
    trendingDaily: 75,
    size: 10 * 1024,
    sizeLabel: "10 KB",
    updatedAt: "2026-04-15",
    preview: false,
    verified: false,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-docker",
    license: "MIT",
  },
  {
    id: "codek-vue-intellisense",
    name: "codek-vue",
    displayName: "Vue Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Vue 3 框架支持。Composition API 补全（ref/reactive/computed/watch），SFC 语法提示，Vue Router/Pinia 代码片段。",
    icon: "VU",
    keywords: ["vue", "vue3", "composition-api", "pinia", "router"],
    categories: ["frameworks"],
    language: "html",
    languages: ["html", "javascript", "typescript"],
    rating: 4.7,
    ratingCount: 460,
    downloads: 3800,
    trendingDaily: 120,
    size: 14 * 1024,
    sizeLabel: "14 KB",
    updatedAt: "2026-05-16",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-vue-intellisense",
    license: "MIT",
  },
  {
    id: "codek-react-intellisense",
    name: "codek-react",
    displayName: "React Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "React 框架支持。Hooks 补全（useState/useEffect/useMemo/useCallback），JSX 语法提示，React Router 代码片段。",
    icon: "RE",
    keywords: ["react", "react-hooks", "jsx", "router"],
    categories: ["frameworks"],
    language: "javascript",
    languages: ["javascript", "typescript", "jsx", "tsx"],
    rating: 4.6,
    ratingCount: 390,
    downloads: 3500,
    trendingDaily: 105,
    size: 12 * 1024,
    sizeLabel: "12 KB",
    updatedAt: "2026-05-14",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-react-intellisense",
    license: "MIT",
  },
  {
    id: "codek-csharp-intellisense",
    name: "codek-csharp",
    displayName: "C# IntelliSense",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "C# 代码补全。LINQ/Task/async/await 智能提示，.NET 标准库方法补全，属性/委托/事件代码片段。",
    icon: "C#",
    keywords: ["csharp", "c#", "dotnet", "intellisense", "linq"],
    categories: ["languages"],
    language: "csharp",
    languages: ["csharp"],
    rating: 4.5,
    ratingCount: 920,
    downloads: 7400,
    trendingDaily: 88,
    size: 30 * 1024,
    sizeLabel: "30 KB",
    updatedAt: "2026-05-10",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-csharp-intellisense",
    license: "MIT",
  },
  {
    id: "codek-ruby-intellisense",
    name: "codek-ruby",
    displayName: "Ruby IntelliSense",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Ruby 代码补全。Array/Hash/String/Enumerable 核心方法，block/proc/lambda 补全，Gem 常用 API 提示。",
    icon: "RB",
    keywords: ["ruby", "intellisense", "completion", "rails", "gem"],
    categories: ["languages"],
    language: "ruby",
    languages: ["ruby"],
    rating: 4.3,
    ratingCount: 540,
    downloads: 4200,
    trendingDaily: 42,
    size: 22 * 1024,
    sizeLabel: "22 KB",
    updatedAt: "2026-05-06",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-ruby-intellisense",
    license: "MIT",
  },
  {
    id: "codek-php-intellisense",
    name: "codek-php",
    displayName: "PHP IntelliSense",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "PHP 代码补全。array/string/pdo/datetime 标准函数，类型声明/属性提升提示，Laravel 常用 Facade 方法。",
    icon: "PH",
    keywords: ["php", "intellisense", "completion", "laravel"],
    categories: ["languages"],
    language: "php",
    languages: ["php"],
    rating: 4.2,
    ratingCount: 610,
    downloads: 5300,
    trendingDaily: 50,
    size: 26 * 1024,
    sizeLabel: "26 KB",
    updatedAt: "2026-05-04",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-php-intellisense",
    license: "MIT",
  },
  {
    id: "codek-swift-intellisense",
    name: "codek-swift",
    displayName: "Swift IntelliSense",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Swift 代码补全。String/Array/Dictionary/Set 标准库，optional/async/await/actor 语言特性， SwiftUI 视图补全。",
    icon: "SW",
    keywords: ["swift", "intellisense", "completion", "swiftui", "ios"],
    categories: ["languages"],
    language: "swift",
    languages: ["swift"],
    rating: 4.4,
    ratingCount: 380,
    downloads: 3100,
    trendingDaily: 38,
    size: 20 * 1024,
    sizeLabel: "20 KB",
    updatedAt: "2026-05-02",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-swift-intellisense",
    license: "MIT",
  },
  {
    id: "codek-kotlin-intellisense",
    name: "codek-kotlin",
    displayName: "Kotlin IntelliSense",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Kotlin 代码补全。协程/Flow/Sequence 补全，扩展函数/数据类/密封类片段，Kotlin 标准库方法提示。",
    icon: "KT",
    keywords: ["kotlin", "intellisense", "completion", "coroutines", "android"],
    categories: ["languages"],
    language: "kotlin",
    languages: ["kotlin"],
    rating: 4.6,
    ratingCount: 490,
    downloads: 4200,
    trendingDaily: 55,
    size: 24 * 1024,
    sizeLabel: "24 KB",
    updatedAt: "2026-04-30",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-kotlin-intellisense",
    license: "MIT",
  },
  {
    id: "codek-scala-intellisense",
    name: "codek-scala",
    displayName: "Scala IntelliSense",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Scala 代码补全。List/Map/Option/Future 标准库，for-comprehension/implicit/given 补全，Akka 常用 API 提示。",
    icon: "SC",
    keywords: ["scala", "intellisense", "completion", "akka", "functional"],
    categories: ["languages"],
    language: "scala",
    languages: ["scala"],
    rating: 4.1,
    ratingCount: 280,
    downloads: 2100,
    trendingDaily: 22,
    size: 22 * 1024,
    sizeLabel: "22 KB",
    updatedAt: "2026-04-28",
    preview: false,
    verified: false,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-scala-intellisense",
    license: "MIT",
  },
  {
    id: "codek-lua-intellisense",
    name: "codek-lua",
    displayName: "Lua IntelliSense",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Lua 代码补全。table/string/math/io/os 标准库，metatable/协程补全，Love2D 游戏框架 API 提示。",
    icon: "LU",
    keywords: ["lua", "intellisense", "completion", "love2d", "neovim"],
    categories: ["languages"],
    language: "lua",
    languages: ["lua"],
    rating: 4.0,
    ratingCount: 320,
    downloads: 2800,
    trendingDaily: 30,
    size: 16 * 1024,
    sizeLabel: "16 KB",
    updatedAt: "2026-04-25",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-lua-intellisense",
    license: "MIT",
  },
  {
    id: "codek-r-intellisense",
    name: "codek-r",
    displayName: "R Language Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "R 语言代码补全。dplyr/ggplot2/tidyr 数据科学包提示，data.frame/vector/list 操作补全，统计函数片段。",
    icon: "R#",
    keywords: ["r", "intellisense", "completion", "data-science", "statistics"],
    categories: ["languages"],
    language: "r",
    languages: ["r"],
    rating: 4.0,
    ratingCount: 210,
    downloads: 1800,
    trendingDaily: 18,
    size: 18 * 1024,
    sizeLabel: "18 KB",
    updatedAt: "2026-04-22",
    preview: false,
    verified: false,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-r-intellisense",
    license: "MIT",
  },
  {
    id: "codek-dart-intellisense",
    name: "codek-dart",
    displayName: "Dart/Flutter Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Dart/Flutter 代码补全。Widget/StatelessWidget/StatefulWidget 补全，async/await/Future/Stream 提示，Flutter 常用组件片段。",
    icon: "DT",
    keywords: ["dart", "flutter", "intellisense", "completion", "widget"],
    categories: ["languages"],
    language: "dart",
    languages: ["dart"],
    rating: 4.5,
    ratingCount: 560,
    downloads: 4600,
    trendingDaily: 62,
    size: 26 * 1024,
    sizeLabel: "26 KB",
    updatedAt: "2026-05-08",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-dart-intellisense",
    license: "MIT",
  },
  {
    id: "codek-elixir-intellisense",
    name: "codek-elixir",
    displayName: "Elixir Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Elixir 代码补全。Enum/Map/List/String 标准库，pattern matching/pipe operator 补全，Phoenix 框架 API 提示。",
    icon: "EX",
    keywords: ["elixir", "intellisense", "completion", "phoenix", "beam"],
    categories: ["languages"],
    language: "elixir",
    languages: ["elixir"],
    rating: 4.1,
    ratingCount: 180,
    downloads: 1400,
    trendingDaily: 15,
    size: 18 * 1024,
    sizeLabel: "18 KB",
    updatedAt: "2026-04-20",
    preview: false,
    verified: false,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-elixir-intellisense",
    license: "MIT",
  },
  {
    id: "codek-haskell-intellisense",
    name: "codek-haskell",
    displayName: "Haskell Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Haskell 代码补全。Prelude/Data.List/Data.Map 标准库，Monad/Functor/Applicative 类型类补全，常用 GHC 扩展提示。",
    icon: "HS",
    keywords: ["haskell", "intellisense", "completion", "monad", "functional"],
    categories: ["languages"],
    language: "haskell",
    languages: ["haskell"],
    rating: 3.9,
    ratingCount: 140,
    downloads: 1100,
    trendingDaily: 12,
    size: 20 * 1024,
    sizeLabel: "20 KB",
    updatedAt: "2026-04-18",
    preview: false,
    verified: false,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-haskell-intellisense",
    license: "MIT",
  },
  {
    id: "codek-typescript-enhanced",
    name: "codek-ts-enhanced",
    displayName: "TypeScript Enhanced",
    version: "1.2.0",
    publisher: "Codek Team",
    description: "TypeScript 增强补全。高级类型工具（Partial/Required/Pick/Omit），泛型约束提示，装饰器补全，tsconfig 智能配置。",
    icon: "T+",
    keywords: ["typescript", "enhanced", "generics", "decorators", "utility-types"],
    categories: ["languages"],
    language: "typescript",
    languages: ["typescript", "tsx"],
    rating: 4.8,
    ratingCount: 1420,
    downloads: 11200,
    trendingDaily: 150,
    size: 18 * 1024,
    sizeLabel: "18 KB",
    updatedAt: "2026-05-17",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-ts-enhanced",
    license: "MIT",
  },
  {
    id: "codek-angular",
    name: "codek-angular",
    displayName: "Angular Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Angular 框架支持。组件/服务/管道/指令补全，RxJS 操作符提示，Angular CLI 代码片段，模板语法智能补全。",
    icon: "NG",
    keywords: ["angular", "framework", "rxjs", "typescript", "components"],
    categories: ["frameworks"],
    language: "typescript",
    languages: ["typescript", "html"],
    rating: 4.3,
    ratingCount: 340,
    downloads: 3200,
    trendingDaily: 45,
    size: 22 * 1024,
    sizeLabel: "22 KB",
    updatedAt: "2026-05-05",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-angular",
    license: "MIT",
  },
  {
    id: "codek-svelte",
    name: "codek-svelte",
    displayName: "Svelte Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Svelte 框架支持。$:/on:bind: 语法补全，SvelteKit 路由提示，store/writable/readable 代码片段，响应式声明补全。",
    icon: "SV",
    keywords: ["svelte", "framework", "sveltekit", "reactive"],
    categories: ["frameworks"],
    language: "html",
    languages: ["html", "javascript", "typescript"],
    rating: 4.4,
    ratingCount: 280,
    downloads: 2600,
    trendingDaily: 55,
    size: 14 * 1024,
    sizeLabel: "14 KB",
    updatedAt: "2026-05-12",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-svelte",
    license: "MIT",
  },
  {
    id: "codek-nextjs",
    name: "codek-nextjs",
    displayName: "Next.js Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Next.js 框架支持。App Router/Server Components 补全，getServerSideProps/getStaticProps 片段，API Route 模板，中间件提示。",
    icon: "NX",
    keywords: ["nextjs", "next", "framework", "ssr", "react"],
    categories: ["frameworks"],
    language: "typescript",
    languages: ["typescript", "javascript", "jsx", "tsx"],
    rating: 4.7,
    ratingCount: 520,
    downloads: 4800,
    trendingDaily: 95,
    size: 16 * 1024,
    sizeLabel: "16 KB",
    updatedAt: "2026-05-15",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-nextjs",
    license: "MIT",
  },
  {
    id: "codek-nuxt",
    name: "codek-nuxt",
    displayName: "Nuxt Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Nuxt 框架支持。auto-imports 补全，server/api routes 提示，useFetch/useAsyncData 代码片段，Nuxt 配置智能补全。",
    icon: "NT",
    keywords: ["nuxt", "nuxt3", "framework", "vue", "ssr"],
    categories: ["frameworks"],
    language: "typescript",
    languages: ["typescript", "javascript", "vue"],
    rating: 4.4,
    ratingCount: 310,
    downloads: 2900,
    trendingDaily: 48,
    size: 14 * 1024,
    sizeLabel: "14 KB",
    updatedAt: "2026-05-10",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-nuxt",
    license: "MIT",
  },
  {
    id: "codek-flask",
    name: "codek-flask",
    displayName: "Flask Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Flask 框架支持。@app.route/@blueprint 路由补全，request/session/g 智能提示，Jinja2 模板片段，SQLAlchemy 集成提示。",
    icon: "FK",
    keywords: ["flask", "python", "framework", "jinja2", "sqlalchemy"],
    categories: ["frameworks"],
    language: "python",
    languages: ["python", "html"],
    rating: 4.2,
    ratingCount: 430,
    downloads: 3800,
    trendingDaily: 35,
    size: 16 * 1024,
    sizeLabel: "16 KB",
    updatedAt: "2026-04-25",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-flask",
    license: "MIT",
  },
  {
    id: "codek-rails",
    name: "codek-rails",
    displayName: "Ruby on Rails Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Rails 框架支持。ActiveRecord 查询补全，Controller/Model/View 片段，路由 helpers 提示，migration 代码片段。",
    icon: "RR",
    keywords: ["rails", "ruby", "framework", "activerecord", "mvc"],
    categories: ["frameworks"],
    language: "ruby",
    languages: ["ruby", "html", "yaml"],
    rating: 4.3,
    ratingCount: 350,
    downloads: 3200,
    trendingDaily: 32,
    size: 22 * 1024,
    sizeLabel: "22 KB",
    updatedAt: "2026-04-22",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-rails",
    license: "MIT",
  },
  {
    id: "codek-gitlens",
    name: "codek-gitlens",
    displayName: "GitLens",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Git 增强工具。行级 blame 注释，文件历史对比，分支比较，commit 搜索，仓库可视化。",
    icon: "GL",
    keywords: ["git", "blame", "history", "diff", "repository"],
    categories: ["tools"],
    language: "plaintext",
    languages: ["plaintext"],
    rating: 4.8,
    ratingCount: 2100,
    downloads: 16800,
    trendingDaily: 180,
    size: 32 * 1024,
    sizeLabel: "32 KB",
    updatedAt: "2026-05-16",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-gitlens",
    license: "MIT",
  },
  {
    id: "codek-remote-ssh",
    name: "codek-remote-ssh",
    displayName: "Remote SSH",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "远程 SSH 开发。连接远程服务器编辑文件，SSH 配置管理，端口转发，远程终端集成。",
    icon: "SS",
    keywords: ["ssh", "remote", "server", "development"],
    categories: ["tools"],
    language: "plaintext",
    languages: ["plaintext"],
    rating: 4.6,
    ratingCount: 890,
    downloads: 7200,
    trendingDaily: 82,
    size: 18 * 1024,
    sizeLabel: "18 KB",
    updatedAt: "2026-05-08",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-remote-ssh",
    license: "MIT",
  },
  {
    id: "codek-rest-client",
    name: "codek-rest-client",
    displayName: "REST Client",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "HTTP 请求客户端。在编辑器中发送 HTTP 请求，支持 GET/POST/PUT/DELETE，环境变量，请求历史，响应预览。",
    icon: "RC",
    keywords: ["rest", "http", "api", "client", "request"],
    categories: ["tools"],
    language: "plaintext",
    languages: ["plaintext", "http"],
    rating: 4.5,
    ratingCount: 760,
    downloads: 6500,
    trendingDaily: 70,
    size: 14 * 1024,
    sizeLabel: "14 KB",
    updatedAt: "2026-05-05",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-rest-client",
    license: "MIT",
  },
  {
    id: "codek-thunder-client",
    name: "codek-thunder-client",
    displayName: "Thunder Client",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "轻量 API 测试工具。集合管理，环境变量，断言测试，GraphQL 支持，cURL 导入导出。",
    icon: "TC",
    keywords: ["thunder", "api", "testing", "http", "graphql"],
    categories: ["tools"],
    language: "plaintext",
    languages: ["plaintext"],
    rating: 4.4,
    ratingCount: 620,
    downloads: 5400,
    trendingDaily: 58,
    size: 16 * 1024,
    sizeLabel: "16 KB",
    updatedAt: "2026-05-02",
    preview: false,
    verified: false,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-thunder-client",
    license: "MIT",
  },
  {
    id: "codek-yaml",
    name: "codek-yaml",
    displayName: "YAML Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "YAML 语言支持。智能缩进，Kubernetes/CircleCI/GitHub Actions schema 验证，锚点/别名补全，自定义 schema。",
    icon: "YM",
    keywords: ["yaml", "kubernetes", "schema", "validation"],
    categories: ["languages"],
    language: "yaml",
    languages: ["yaml"],
    rating: 4.6,
    ratingCount: 1100,
    downloads: 9200,
    trendingDaily: 95,
    size: 20 * 1024,
    sizeLabel: "20 KB",
    updatedAt: "2026-05-12",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-yaml",
    license: "MIT",
  },
  {
    id: "codek-toml",
    name: "codek-toml",
    displayName: "TOML Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "TOML 语言支持。Cargo.toml/pyproject.toml 智能补全，表/数组/内联表语法提示，schema 验证。",
    icon: "TM",
    keywords: ["toml", "cargo", "pyproject", "configuration"],
    categories: ["languages"],
    language: "toml",
    languages: ["toml"],
    rating: 4.2,
    ratingCount: 380,
    downloads: 3200,
    trendingDaily: 35,
    size: 12 * 1024,
    sizeLabel: "12 KB",
    updatedAt: "2026-04-28",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-toml",
    license: "MIT",
  },
  {
    id: "codek-graphql",
    name: "codek-graphql",
    displayName: "GraphQL Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "GraphQL 语言支持。Query/Mutation/Subscription 补全，schema 定义提示，变量/片段补全，内省查询。",
    icon: "GQ",
    keywords: ["graphql", "schema", "query", "mutation", "api"],
    categories: ["languages"],
    language: "graphql",
    languages: ["graphql"],
    rating: 4.5,
    ratingCount: 420,
    downloads: 3800,
    trendingDaily: 42,
    size: 16 * 1024,
    sizeLabel: "16 KB",
    updatedAt: "2026-05-06",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-graphql",
    license: "MIT",
  },
  {
    id: "codek-prisma",
    name: "codek-prisma",
    displayName: "Prisma Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Prisma ORM 支持。schema.prisma 语法补全，model/field/relation 定义提示，迁移命令片段，Client 查询补全。",
    icon: "PR",
    keywords: ["prisma", "orm", "database", "schema", "migration"],
    categories: ["tools"],
    language: "prisma",
    languages: ["prisma", "typescript", "javascript"],
    rating: 4.6,
    ratingCount: 530,
    downloads: 4600,
    trendingDaily: 62,
    size: 18 * 1024,
    sizeLabel: "18 KB",
    updatedAt: "2026-05-10",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-prisma",
    license: "MIT",
  },
  {
    id: "codek-tailwindcss",
    name: "codek-tailwindcss",
    displayName: "Tailwind CSS Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Tailwind CSS 支持。class 名称智能补全，响应式/状态变体提示，自定义配置读取，颜色预览。",
    icon: "TW",
    keywords: ["tailwind", "css", "utility", "framework", "classes"],
    categories: ["tools"],
    language: "html",
    languages: ["html", "vue", "jsx", "tsx", "javascript", "typescript"],
    rating: 4.8,
    ratingCount: 1680,
    downloads: 13400,
    trendingDaily: 165,
    size: 24 * 1024,
    sizeLabel: "24 KB",
    updatedAt: "2026-05-14",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-tailwindcss",
    license: "MIT",
  },
  {
    id: "codek-one-dark-pro",
    name: "codek-one-dark-pro",
    displayName: "One Dark Pro",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "One Dark Pro 主题。基于 Atom One Dark 配色方案，精心调校的语法高亮，支持所有语言。",
    icon: "1D",
    keywords: ["theme", "dark", "one-dark", "atom", "color"],
    categories: ["themes"],
    language: "plaintext",
    languages: [],
    rating: 4.9,
    ratingCount: 2800,
    downloads: 22400,
    trendingDaily: 210,
    size: 8 * 1024,
    sizeLabel: "8 KB",
    updatedAt: "2026-05-16",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-one-dark-pro",
    license: "MIT",
  },
  {
    id: "codek-dracula",
    name: "codek-dracula",
    displayName: "Dracula Theme",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Dracula 暗色主题。经典 Dracula 配色，高对比度语法高亮，舒适的阅读体验。",
    icon: "DR",
    keywords: ["theme", "dark", "dracula", "color"],
    categories: ["themes"],
    language: "plaintext",
    languages: [],
    rating: 4.7,
    ratingCount: 1920,
    downloads: 15600,
    trendingDaily: 145,
    size: 6 * 1024,
    sizeLabel: "6 KB",
    updatedAt: "2026-05-12",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-dracula",
    license: "MIT",
  },
  {
    id: "codek-nord",
    name: "codek-nord",
    displayName: "Nord Theme",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Nord 极地主题。北极配色灵感，低对比度护眼设计，清冷的蓝灰色调。",
    icon: "ND",
    keywords: ["theme", "dark", "nord", "arctic", "color"],
    categories: ["themes"],
    language: "plaintext",
    languages: [],
    rating: 4.6,
    ratingCount: 1340,
    downloads: 10800,
    trendingDaily: 98,
    size: 6 * 1024,
    sizeLabel: "6 KB",
    updatedAt: "2026-05-08",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-nord",
    license: "MIT",
  },
  {
    id: "codek-solarized",
    name: "codek-solarized",
    displayName: "Solarized Theme",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Solarized 主题。经典 Solarized 明暗双模式，科学配色方案，精确的对比度平衡。",
    icon: "SO",
    keywords: ["theme", "solarized", "light", "dark", "color"],
    categories: ["themes"],
    language: "plaintext",
    languages: [],
    rating: 4.5,
    ratingCount: 1180,
    downloads: 9400,
    trendingDaily: 85,
    size: 8 * 1024,
    sizeLabel: "8 KB",
    updatedAt: "2026-05-04",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-solarized",
    license: "MIT",
  },
  {
    id: "codek-monokai-pro",
    name: "codek-monokai-pro",
    displayName: "Monokai Pro Theme",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Monokai Pro 主题。经典 Monokai 增强版，丰富色彩层次，代码结构一目了然。",
    icon: "MK",
    keywords: ["theme", "dark", "monokai", "pro", "color"],
    categories: ["themes"],
    language: "plaintext",
    languages: [],
    rating: 4.7,
    ratingCount: 1560,
    downloads: 12200,
    trendingDaily: 120,
    size: 6 * 1024,
    sizeLabel: "6 KB",
    updatedAt: "2026-05-10",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-monokai-pro",
    license: "MIT",
  },
  {
    id: "codek-jest",
    name: "codek-jest",
    displayName: "Jest Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Jest 测试框架支持。describe/it/expect 补全，matcher 方法提示，mock/spy 代码片段，快照测试模板。",
    icon: "JE",
    keywords: ["jest", "testing", "javascript", "typescript", "mock"],
    categories: ["tools"],
    language: "javascript",
    languages: ["javascript", "typescript", "jsx", "tsx"],
    rating: 4.6,
    ratingCount: 980,
    downloads: 8400,
    trendingDaily: 92,
    size: 14 * 1024,
    sizeLabel: "14 KB",
    updatedAt: "2026-05-06",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-jest",
    license: "MIT",
  },
  {
    id: "codek-vitest",
    name: "codek-vitest",
    displayName: "Vitest Support",
    version: "1.0.0",
    publisher: "Codek Team",
    description: "Vitest 测试框架支持。兼容 Jest API 的极速测试，describe/it/expect 补全，Vite 原生集成，覆盖率配置片段。",
    icon: "VI",
    keywords: ["vitest", "testing", "vite", "javascript", "typescript"],
    categories: ["tools"],
    language: "typescript",
    languages: ["javascript", "typescript", "jsx", "tsx"],
    rating: 4.7,
    ratingCount: 720,
    downloads: 6200,
    trendingDaily: 88,
    size: 12 * 1024,
    sizeLabel: "12 KB",
    updatedAt: "2026-05-14",
    preview: false,
    verified: true,
    downloadUrl: "",
    repository: "https://github.com/codek/codek-vitest",
    license: "MIT",
  },
]

function matchEntry(entry: MarketplaceEntry, filter: MarketplaceFilter): boolean {
  if (filter.search) {
    const q = filter.search.toLowerCase()
    const haystack = [
      entry.displayName,
      entry.name,
      entry.description,
      entry.publisher,
      ...entry.keywords,
      ...entry.categories,
    ].join(" ").toLowerCase()
    if (!haystack.includes(q)) return false
  }
  if (filter.category && !entry.categories.includes(filter.category as never)) return false
  if (filter.language && entry.language !== filter.language && !entry.languages?.includes(filter.language)) return false
  return true
}

function sortEntries(entries: MarketplaceEntry[], filter: MarketplaceFilter): MarketplaceEntry[] {
  const order = filter.sortOrder === "asc" ? 1 : -1
  const sorted = [...entries]
  switch (filter.sortBy) {
    case "downloads":
      sorted.sort((a, b) => (a.downloads - b.downloads) * order)
      break
    case "rating":
      sorted.sort((a, b) => (a.rating - b.rating) * order)
      break
    case "trending":
      sorted.sort((a, b) => (a.trendingDaily - b.trendingDaily) * order)
      break
    case "updated":
      sorted.sort((a, b) => a.updatedAt.localeCompare(b.updatedAt) * order)
      break
    default:
      break
  }
  return sorted
}

export function fetchMarketplace(filter?: MarketplaceFilter): MarketplaceEntry[] {
  let entries = [...MARKETPLACE_DATA]
  if (filter) {
    entries = entries.filter((e) => matchEntry(e, filter))
    entries = sortEntries(entries, filter)
  }
  return entries
}

export function getMarketplaceEntry(id: string): MarketplaceEntry | undefined {
  return MARKETPLACE_DATA.find((e) => e.id === id)
}

export function getFeaturedPlugins(): MarketplaceEntry[] {
  return MARKETPLACE_DATA.filter((e) => e.downloads > 10000)
    .sort((a, b) => b.rating - a.rating)
    .slice(0, 6)
}

export function getRecommendedPlugins(installedIds: string[]): MarketplaceEntry[] {
  const installedSet = new Set(installedIds)
  return MARKETPLACE_DATA.filter((e) => !installedSet.has(e.id))
    .sort((a, b) => b.downloads - a.downloads)
    .slice(0, 4)
}

export const CATEGORY_LABELS: Record<string, string> = {
  languages: "语言",
  snippets: "代码片段",
  linters: "代码检查",
  themes: "主题",
  formatters: "格式化",
  debuggers: "调试",
  frameworks: "框架",
  tools: "工具",
  other: "其他",
}

export const CATEGORY_ICONS: Record<string, string> = {
  languages: "{}",
  snippets: "✂",
  linters: "✓",
  themes: "🎨",
  formatters: "≡",
  debuggers: "🐛",
  frameworks: "⚙",
  tools: "🔧",
  other: "📦",
}